# Generated by Django 4.0.6 on 2022-09-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_longgui_logging_mysql', '0005_alter_tenantlogconfig_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='request_path',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='status_code',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='username',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间'),
        ),
    ]
