# Generated by Django 3.2.13 on 2022-05-31 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('com_longgui_account_life_arkid', '0002_auto_20220531_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexpiration',
            old_name='user',
            new_name='target',
        ),
    ]
