name: arkid saas cicd

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'kustomize/**'
      - 'README.md'
jobs:
  dev2test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login harbor
      uses: docker/login-action@v1
      with:
        registry: harbor.longguikeji.com
        username: ${{ secrets.HARBORUSER }}
        password: ${{ secrets.HARBORPWD }}
    - id: get-short-id
      run: |
        id=$(echo ${{github.sha}})
        echo "::set-output name=id::${id: 0 :8}"
    - run: echo "${{steps.get-short-id.outputs.id}}"
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64
        build-args: |
          ARKID_TAG=v2dev
        push: true
        tags: |
          harbor.longguikeji.com/ark-develops/arkid-saas:${{ github.run_number }}-${{steps.get-short-id.outputs.id}}
          harbor.longguikeji.com/ark-develops/arkid-saas:${{ github.run_number }}
          harbor.longguikeji.com/ark-develops/arkid-saas:latest
    - name: deploy to cluster
      uses: steebchen/kubectl@v2.0.0
      with: # defaults to latest kubectl binary version
        config: ${{ secrets.KUBE_CONFIG_ARKOS }}
        command: -n dev-arkidv2saas --insecure-skip-tls-verify=true set image --record deployment/dev-arkidv2saas-be cpextensionroot=harbor.longguikeji.com/ark-develops/arkid-saas:${{ github.run_number }} arkid-be=harbor.longguikeji.com/ark-develops/arkid-saas:${{ github.run_number }}
    
