package='com.longgui.auto.form.fill'
name='帐密代填插件'
version='1.2'
labels='auto-form-fill'
homepage='http://longguikeji.gitee.io/arkid/%20%E5%85%B6%E5%AE%83%E6%8F%92%E4%BB%B6/com_longgui_auto_form_fill/'
logo=''
author='fanhe@longguikeji.com'
