# Generated by Django 2.0.7 on 2019-01-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='accept_user',
            field=models.BooleanField(default=True),
        ),
    ]
