# Generated by Django 2.0.7 on 2019-01-16 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0004_auto_20190115_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dingdept',
            name='dept',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ding_dept', to='oneid_meta.Dept'),
        ),
    ]
