# Generated by Django 2.0.7 on 2019-01-17 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0005_auto_20190116_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deptperm',
            old_name='onwer',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='groupperm',
            old_name='onwer',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='userperm',
            old_name='onwer',
            new_name='owner',
        ),
    ]
