# Generated by Django 2.0.7 on 2019-01-18 09:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0006_auto_20190117_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='DingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('uid', models.IntegerField(verbose_name='钉钉角色id')),
                ('data', models.TextField(blank=True, default='{}', verbose_name='钉钉角色详细信息(JSON)')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ding_group', to='oneid_meta.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
