# Generated by Django 2.0.7 on 2019-01-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0007_dinggroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='remark',
            field=models.TextField(blank=True, default='', verbose_name='详细介绍'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, verbose_name='组名称'),
        ),
        migrations.AlterField(
            model_name='group',
            name='remark',
            field=models.TextField(blank=True, default='', verbose_name='选项介绍'),
        ),
        migrations.AlterField(
            model_name='perm',
            name='uid',
            field=models.CharField(max_length=255, unique=True, verbose_name='权限唯一标识'),
        ),
        migrations.AlterUniqueTogether(
            name='deptmember',
            unique_together={('user', 'owner')},
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('user', 'owner')},
        ),
    ]
