# Generated by Django 2.0.7 on 2019-02-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0007_auto_20190214_1736'),
        ('oneid_meta', '0013_creata_perm_ark_all'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthAPP',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('oauth2_provider.application',),
        ),
    ]
