# Generated by Django 2.0.7 on 2019-02-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0014_oauthapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='editable',
            field=models.BooleanField(default=True, verbose_name='是否可编辑、删除'),
        ),
        migrations.AddField(
            model_name='perm',
            name='default_value',
            field=models.BooleanField(default=False, verbose_name='默认授权还是拒绝'),
        ),
        migrations.AddField(
            model_name='perm',
            name='editable',
            field=models.BooleanField(default=True, verbose_name='是否可编辑、删除'),
        ),
    ]
