# Generated by Django 2.0.7 on 2019-04-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0017_init_orgnazation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='from_register',
            field=models.BooleanField(default=False, verbose_name='是否来自自己注册'),
        ),
    ]
