# Generated by Django 2.0.7 on 2019-04-19 09:56

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0018_user_from_register'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('isolated_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='allow_any_user',
            field=models.BooleanField(default=False, verbose_name='任何OneID用户都可以访问'),
        ),
    ]
