# Generated by Django 2.0.7 on 2019-04-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0022_load_config_from_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='dingconfig',
            name='app_valid',
            field=models.BooleanField(default=False, verbose_name='APP 配置是否正确'),
        ),
        migrations.AddField(
            model_name='dingconfig',
            name='corp_valid',
            field=models.BooleanField(default=False, verbose_name='Corp 配置是否正确'),
        ),
        migrations.AlterField(
            model_name='dingconfig',
            name='app_secret',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='APP SECRET'),
        ),
    ]
