# Generated by Django 2.0.7 on 2019-05-29 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0027_auto_20190528_1929'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deptperm',
            unique_together={('owner', 'perm')},
        ),
        migrations.AlterUniqueTogether(
            name='groupperm',
            unique_together={('owner', 'perm')},
        ),
        migrations.AlterUniqueTogether(
            name='userperm',
            unique_together={('owner', 'perm')},
        ),
    ]
