# Generated by Django 2.0.7 on 2019-05-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0028_auto_20190529_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='头像'),
        ),
    ]
