# Generated by Django 2.0.7 on 2019-07-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0036_smsconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='top',
            field=models.CharField(blank=True, default='root', max_length=255, verbose_name='范围顶点uid'),
        ),
    ]
