# Generated by Django 2.0.7 on 2019-07-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0038_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perm',
            name='action',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='操作行为'),
        ),
        migrations.AlterField(
            model_name='perm',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='权限名称'),
        ),
        migrations.AlterField(
            model_name='perm',
            name='subject',
            field=models.CharField(blank=True, default='app', max_length=255, verbose_name='权限分类'),
        ),
        migrations.AlterField(
            model_name='perm',
            name='uid',
            field=models.CharField(blank=True, default='', max_length=255, unique=True, verbose_name='权限唯一标识'),
        ),
    ]
