# Generated by Django 2.0.7 on 2019-07-17 07:12

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0041_app_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept',
            name='node_scope',
            field=jsonfield.fields.JSONField(blank=True, default=[], verbose_name='指定节点node_uids'),
        ),
        migrations.AddField(
            model_name='dept',
            name='user_scope',
            field=jsonfield.fields.JSONField(blank=True, default=[], verbose_name='指定人usernames'),
        ),
        migrations.AddField(
            model_name='dept',
            name='visibility',
            field=models.IntegerField(blank=True, choices=[(1, '所有人可见'), (2, '节点成员可见'), (3, '节点成员及其下属节点均可见'), (4, '只对指定人、节点可见'), (5, '所有人不可见')], default=1, verbose_name='可见范围类型'),
        ),
        migrations.AddField(
            model_name='group',
            name='node_scope',
            field=jsonfield.fields.JSONField(blank=True, default=[], verbose_name='指定节点node_uids'),
        ),
        migrations.AddField(
            model_name='group',
            name='user_scope',
            field=jsonfield.fields.JSONField(blank=True, default=[], verbose_name='指定人usernames'),
        ),
        migrations.AddField(
            model_name='group',
            name='visibility',
            field=models.IntegerField(blank=True, choices=[(1, '所有人可见'), (2, '节点成员可见'), (3, '节点成员及其下属节点均可见'), (4, '只对指定人、节点可见'), (5, '所有人不可见')], default=1, verbose_name='可见范围类型'),
        ),
    ]
