# Generated by Django 2.0.7 on 2019-07-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0042_auto_20190717_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='index',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='应用首页'),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='color',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='主题色值'),
        ),
        migrations.AlterField(
            model_name='app',
            name='logo',
            field=models.TextField(blank=True, default='', null=True, verbose_name='LOGO'),
        ),
    ]
