# Generated by Django 2.0.7 on 2019-07-22 04:26

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0043_auto_20190719_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managergroup',
            name='all_apps',
        ),
        migrations.RemoveField(
            model_name='managergroup',
            name='dept_subject',
        ),
        migrations.RemoveField(
            model_name='managergroup',
            name='depts',
        ),
        migrations.AddField(
            model_name='managergroup',
            name='nodes',
            field=jsonfield.fields.JSONField(blank=True, default=[], verbose_name='节点uids'),
        ),
        migrations.AddField(
            model_name='managergroup',
            name='perms',
            field=jsonfield.fields.JSONField(blank=True, default=[], verbose_name='权限uids'),
        ),
        migrations.AddField(
            model_name='managergroup',
            name='scope_subject',
            field=models.IntegerField(choices=[(1, '所在节点及下级节点'), (2, '指定节点和人员')], default=1, verbose_name='管理范围类型'),
        ),
        migrations.AddField(
            model_name='managergroup',
            name='users',
            field=jsonfield.fields.JSONField(blank=True, default=[], verbose_name='人员uids'),
        ),
        migrations.AlterField(
            model_name='managergroup',
            name='apps',
            field=jsonfield.fields.JSONField(blank=True, default=[], verbose_name='应用uids'),
        ),
    ]
