# Generated by Django 2.0.7 on 2019-07-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0046_emailconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='origin',
            field=models.IntegerField(choices=[(0, '脚本添加'), (1, '管理员添加'), (2, '用户名注册'), (3, '手机注册'), (4, '邮箱注册')], default=0, verbose_name='账号来源'),
        ),
    ]
