# Generated by Django 2.0.7 on 2019-07-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0047_user_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountconfig',
            name='email_register',
        ),
        migrations.RemoveField(
            model_name='accountconfig',
            name='email_reset_pwd',
        ),
        migrations.RemoveField(
            model_name='accountconfig',
            name='mobile_register',
        ),
        migrations.RemoveField(
            model_name='accountconfig',
            name='mobile_reset_pwd',
        ),
        migrations.RemoveField(
            model_name='accountconfig',
            name='username_register',
        ),
        migrations.AddField(
            model_name='accountconfig',
            name='allow_email',
            field=models.BooleanField(default=False, verbose_name='是否允许邮箱(注册、)登录、找回密码'),
        ),
        migrations.AddField(
            model_name='accountconfig',
            name='allow_mobile',
            field=models.BooleanField(default=False, verbose_name='是否允许手机(注册、)登录、找回密码'),
        ),
        migrations.AddField(
            model_name='accountconfig',
            name='allow_register',
            field=models.BooleanField(default=False, verbose_name='是否开放注册'),
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='配置是否有效'),
        ),
        migrations.AddField(
            model_name='smsconfig',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='配置是否有效'),
        ),
        migrations.AddField(
            model_name='smsconfig',
            name='template_activate',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='用户激活文案模板ID'),
        ),
        migrations.AddField(
            model_name='smsconfig',
            name='template_reset_mobile',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='用户重置手机文案模板ID'),
        ),
    ]
