# Generated by Django 2.0.13 on 2019-09-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '00052_add_extern'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hiredate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='subject',
            field=models.CharField(choices=[('user', '内部联系人'), ('extern_user', '外部联系人')], default='user', max_length=128, verbose_name='字段分类'),
        ),
    ]
