# Generated by Django 2.0.13 on 2019-09-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0054_auto_20190910_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_active_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近活跃时间'),
        ),
    ]
