# Generated by Django 2.0.13 on 2019-10-14 12:23

from django.db import migrations, models
import django.db.models.deletion
import oneid_meta.models.config
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('oneid_meta', '0055_user_last_active_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlipayConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('app_id', models.CharField(blank=True, default='', max_length=255, verbose_name='QR APP ID')),
                ('app_private_key', models.CharField(blank=True, default='', max_length=2000, verbose_name='QR APP SECRET')),
                ('alipay_public_key', models.CharField(blank=True, default='', max_length=2000, verbose_name='QR APP SECRET')),
                ('qr_app_valid', models.BooleanField(default=False, verbose_name='扫码登录APP配置是否正确')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alipay_config', to='sites.Site')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, oneid_meta.models.config.SingletonConfigMixin),
        ),
        migrations.CreateModel(
            name='AlipayUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('alipay_id', models.TextField(blank=True, max_length=255, verbose_name='支付宝ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='alipay_user', to='oneid_meta.User', verbose_name='用户')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='accountconfig',
            name='allow_alipay_qr',
            field=models.BooleanField(default=False, verbose_name='是否开放支付宝扫码登录'),
        ),
        migrations.AddField(
            model_name='accountconfig',
            name='allow_ding_qr',
            field=models.BooleanField(default=False, verbose_name='是否开放钉钉扫码登录'),
        ),
        migrations.AddField(
            model_name='dingconfig',
            name='qr_app_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='QR APP ID'),
        ),
        migrations.AddField(
            model_name='dingconfig',
            name='qr_app_secret',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='QR APP SECRET'),
        ),
        migrations.AddField(
            model_name='dingconfig',
            name='qr_app_valid',
            field=models.BooleanField(default=False, verbose_name='扫码登录APP配置是否正确'),
        ),
        migrations.AddField(
            model_name='dinguser',
            name='ding_id',
            field=models.TextField(blank=True, max_length=255, verbose_name='钉钉ID'),
        ),
        migrations.AddField(
            model_name='dinguser',
            name='open_id',
            field=models.TextField(blank=True, max_length=255, verbose_name='用户在当前开放应用内的唯一标识'),
        ),
        migrations.AddField(
            model_name='dinguser',
            name='union_id',
            field=models.TextField(blank=True, max_length=255, verbose_name='用户在当前开放应用所属的钉钉开放平台账号内的唯一标识'),
        ),
    ]
