# Generated by Django 2.0.13 on 2019-10-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0056_auto_20190929_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountconfig',
            name='allow_ding',
            field=models.BooleanField(default=False, verbose_name='是否开放钉钉（注册）登录'),
        ),
        migrations.AddField(
            model_name='dingconfig',
            name='sns_app_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='APP ID'),
        ),
        migrations.AddField(
            model_name='dingconfig',
            name='sns_app_secret',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='APP ID SECRET'),
        ),
        migrations.AddField(
            model_name='dingconfig',
            name='sns_app_valid',
            field=models.BooleanField(default=False, verbose_name='扫码登录APP 配置是否正确'),
        ),
    ]
