# Generated by Django 2.0.13 on 2019-10-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0056_auto_20191014_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alipayconfig',
            name='alipay_public_key',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='ALIPAY PUBLIC KEY'),
        ),
        migrations.AlterField(
            model_name='alipayconfig',
            name='app_private_key',
            field=models.CharField(blank=True, default='', max_length=1600, verbose_name='APP PVIVATE KEY'),
        ),
    ]
