# Generated by Django 2.0.13 on 2019-10-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0057_auto_20191008_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountconfig',
            name='allow_ding',
        ),
        migrations.AddField(
            model_name='accountconfig',
            name='allow_ding_qr',
            field=models.BooleanField(default=False, verbose_name='是否开放钉钉扫码登录'),
        ),
    ]
