# Generated by Django 2.0.13 on 2019-10-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0057_auto_20191009_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dingconfig',
            name='qr_app_valid',
            field=models.BooleanField(default=False, verbose_name='扫码登录APP配置是否正确'),
        ),
    ]
