# Generated by Django 2.0.13 on 2019-10-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0057_auto_20191019_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alipayconfig',
            name='alipay_public_key',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='ALIPAY PUBLIC KEY'),
        ),
        migrations.AlterField(
            model_name='alipayconfig',
            name='app_private_key',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='APP PVIVATE KEY'),
        ),
    ]
