# Generated by Django 2.0.13 on 2019-10-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0058_auto_20191008_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dingconfig',
            old_name='sns_app_valid',
            new_name='qr_app_valid',
        ),
        migrations.RemoveField(
            model_name='dingconfig',
            name='sns_app_id',
        ),
        migrations.RemoveField(
            model_name='dingconfig',
            name='sns_app_secret',
        ),
        migrations.AddField(
            model_name='dingconfig',
            name='qr_app_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='QR APP ID'),
        ),
        migrations.AddField(
            model_name='dingconfig',
            name='qr_app_secret',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='QR APP SECRET'),
        ),
    ]
