# Generated by Django 2.0.13 on 2019-10-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0058_auto_20191012_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='require_reset_password',
            field=models.BooleanField(default=False, verbose_name='是否需要重置密码'),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='nickname',
            field=models.CharField(blank=True, default='ArkID', max_length=128, verbose_name='邮件发送人落款'),
        ),
    ]
