# Generated by Django 2.0.13 on 2019-10-12 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0058_auto_20191012_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dingconfig',
            name='qr_callback_url',
        ),
    ]
