# Generated by Django 2.0.13 on 2019-10-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0059_auto_20191021_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alipayuser',
            name='alipay_user_id',
            field=models.TextField(blank=True, max_length=255, verbose_name='支付宝ID'),
        ),
    ]
