# Generated by Django 2.0.13 on 2019-11-01 12:39

from django.db import migrations, models
import django.db.models.deletion
import oneid_meta.models.config
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('oneid_meta', '0061_auto_20191029_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='QqConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('app_id', models.CharField(blank=True, default='', max_length=255, verbose_name='APP ID')),
                ('app_key', models.CharField(blank=True, default='', max_length=255, verbose_name='APP SECRET')),
                ('redirect_uri', models.CharField(blank=True, default='', max_length=255, verbose_name='REDIRECT URI')),
                ('qr_app_valid', models.BooleanField(default=False, verbose_name='扫码登录是否配置正确')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qq_config', to='sites.Site')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, oneid_meta.models.config.SingletonConfigMixin),
        ),
        migrations.CreateModel(
            name='QqUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('open_id', models.TextField(blank=True, max_length=255, verbose_name='qq平台openid')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='qq_user', to='oneid_meta.User', verbose_name='用户')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='accountconfig',
            name='allow_qq_qr',
            field=models.BooleanField(default=False, verbose_name='是否开放qq扫码登录'),
        ),
    ]
