# Generated by Django 2.0.13 on 2019-11-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0062_auto_20191102_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinguser',
            name='account',
            field=models.CharField(blank=True, max_length=64, verbose_name='钉钉账号(手机)'),
        ),
        migrations.AlterField(
            model_name='dinguser',
            name='uid',
            field=models.CharField(blank=True, max_length=255, verbose_name='员工在企业内的唯一标识'),
        ),
    ]
