# Generated by Django 2.0.13 on 2019-11-15 06:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0064_auto_20191108_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('domain', models.CharField(max_length=255, verbose_name='登录域名')),
                ('username', models.CharField(default='', max_length=255, null=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=512, verbose_name='密码、token')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='perm',
            name='sub_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oneid_meta.SubAccount', verbose_name='子账号'),
        ),
    ]
