# Generated by Django 2.0.13 on 2019-11-22 10:16

from django.db import migrations, models
import django.db.models.deletion
import oneid_meta.models.config
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('oneid_meta', '0065_auto_20191115_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinioConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('end_point', models.CharField(blank=True, default='', max_length=225, verbose_name='END POINT')),
                ('access_key', models.CharField(blank=True, default='', max_length=225, verbose_name='ACCESS KEY')),
                ('secret_key', models.CharField(blank=True, default='', max_length=225, verbose_name='SECRET KEY')),
                ('secure', models.BooleanField(default=True, max_length=225, verbose_name='SECURE')),
                ('location', models.CharField(blank=True, default='', max_length=225, verbose_name='LOCATION')),
                ('bucket', models.CharField(blank=True, default='', max_length=225, verbose_name='BUCKET')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='minio_config', to='sites.Site')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, oneid_meta.models.config.SingletonConfigMixin),
        ),
        migrations.CreateModel(
            name='StorageMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('method', models.CharField(blank=True, default='local', max_length=225, verbose_name='STORAGE METHOD')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_method', to='sites.Site')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, oneid_meta.models.config.SingletonConfigMixin),
        ),
    ]
