# Generated by Django 2.0.13 on 2019-12-10 04:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0066_minioconfig_storageconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=255, verbose_name='组织名')),
                ('dept_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oneid_meta.Dept', verbose_name='部门节点')),
                ('direct_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_uid', to='oneid_meta.Group', verbose_name='直属成员节点')),
                ('group_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oneid_meta.Group', verbose_name='组节点')),
                ('label_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_uid', to='oneid_meta.Group', verbose_name='标签节点')),
                ('manager_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_uid', to='oneid_meta.Group', verbose_name='管理员节点')),
                ('role_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_uid', to='oneid_meta.Group', verbose_name='角色节点')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
