# Generated by Django 2.0.13 on 2019-12-20 09:19

from django.db import migrations, models
import django.db.models.deletion
import oneid_meta.models.config
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('oneid_meta', '0067_samlapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdPConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('cert', models.CharField(blank=True, default='', max_length=2500, verbose_name='cert')),
                ('key', models.CharField(blank=True, default='', max_length=2500, verbose_name='key')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='idp_config', to='sites.Site')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, oneid_meta.models.config.SingletonConfigMixin),
        ),
        migrations.AlterField(
            model_name='samlapp',
            name='xmldata',
            field=models.CharField(blank=True, max_length=5000, verbose_name='本地SP元数据'),
        ),
    ]
