# Generated by Django 2.0.13 on 2019-12-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0067_samlapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='权限名称'),
        ),
    ]
