# Generated by Django 2.0.13 on 2019-11-23 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0067_auto_20191123_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageconfig',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_config', to='sites.Site'),
        ),
    ]
