# Generated by Django 2.0.13 on 2019-12-24 08:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0067_samlapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=255, verbose_name='组织名')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oneid_meta.Dept', verbose_name='部门节点')),
                ('direct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct', to='oneid_meta.Group', verbose_name='直属成员节点')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oneid_meta.Group', verbose_name='组节点')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label', to='oneid_meta.Group', verbose_name='标签节点')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='oneid_meta.Group', verbose_name='管理员节点')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oneid_meta.User', verbose_name='所有者')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='oneid_meta.Group', verbose_name='角色节点')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='current_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oneid_meta.Org'),
        ),
    ]
