# Generated by Django 2.0.13 on 2019-12-12 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0067_org'),
    ]

    operations = [
        migrations.RenameField(
            model_name='org',
            old_name='dept_uid',
            new_name='dept',
        ),
        migrations.RenameField(
            model_name='org',
            old_name='group_uid',
            new_name='group',
        ),
        migrations.RemoveField(
            model_name='org',
            name='direct_uid',
        ),
        migrations.RemoveField(
            model_name='org',
            name='label_uid',
        ),
        migrations.RemoveField(
            model_name='org',
            name='manager_uid',
        ),
        migrations.RemoveField(
            model_name='org',
            name='role_uid',
        ),
        migrations.AddField(
            model_name='org',
            name='direct',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='direct', to='oneid_meta.Group', verbose_name='直属成员节点'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='org',
            name='label',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='label', to='oneid_meta.Group', verbose_name='标签节点'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='org',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='oneid_meta.Group', verbose_name='管理员节点'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='org',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='oneid_meta.Group', verbose_name='角色节点'),
            preserve_default=False,
        ),
    ]
