# Generated by Django 2.0.13 on 2019-12-17 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0068_auto_20191212_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oneid_meta.User', verbose_name='所有者'),
            preserve_default=False,
        ),
    ]
