# Generated by Django 2.0.13 on 2020-01-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0068_auto_20191223_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='dingconfig',
            name='sync_state',
            field=models.CharField(blank=True, choices=[('pull', '拉取'), ('push', '推送'), ('', '断开')], default='', max_length=128, verbose_name='同步钉钉账户方向'),
        ),
    ]
