# Generated by Django 2.0.13 on 2020-03-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0068_auto_20191223_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsconfig',
            name='template_login',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='登录文案模板ID'),
        ),
    ]