# Generated by Django 2.0.13 on 2020-02-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0069_dingconfig_sync_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dingconfig',
            name='sync_state',
            field=models.CharField(choices=[('pull', '拉取'), ('push', '推送'), ('', '断开')], default='pull', max_length=128, verbose_name='同步钉钉账户方向'),
        ),
    ]
