# Generated by Django 2.0.13 on 2019-12-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0069_app_owner'),
        ('oneid_meta', '0068_auto_20191223_1116'),
    ]

    operations = [
    ]
