# Generated by Django 2.0.13 on 2020-02-08 15:40

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0070_default_org'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('isolated_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='employee_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hiredate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='remark',
        ),
    ]
