# Generated by Django 2.0.13 on 2020-01-03 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0070_merge_20191226_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oneid_meta.Org'),
        ),
    ]
