# Generated by Django 2.2.10 on 2020-04-11 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0071_auto_20200208_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oneid_meta.Org', verbose_name='组织'),
        ),
    ]
