# Generated by Django 2.2.10 on 2020-04-20 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0072_auto_20200411_1658'),
        ('oneid_meta', '0072_auto_20200413_1555'),
    ]

    operations = [
    ]
