# Generated by Django 2.0.13 on 2020-02-03 10:28

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0072_default_org'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('isolated_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='companyconfig',
            name='site',
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='org',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='company_config', to='oneid_meta.Org'),
            preserve_default=False,
        ),
    ]
