# Generated by Django 2.0.13 on 2020-02-04 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0073_auto_20200203_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='org',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='oneid_meta.Org'),
            preserve_default=False,
        ),
    ]
