# Generated by Django 2.2.10 on 2020-06-30 09:11

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0073_merge_20200420_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='appgroup',
            name='node_scope',
            field=jsonfield.fields.JSONField(blank=True, default=[], verbose_name='指定节点node_uids'),
        ),
        migrations.AddField(
            model_name='appgroup',
            name='order_no',
            field=models.IntegerField(default=0, verbose_name='排序号'),
        ),
        migrations.AddField(
            model_name='appgroup',
            name='user_scope',
            field=jsonfield.fields.JSONField(blank=True, default=[], verbose_name='指定人usernames'),
        ),
        migrations.AddField(
            model_name='appgroup',
            name='visibility',
            field=models.IntegerField(blank=True, choices=[(1, '所有人可见'), (2, '节点成员可见'), (3, '节点成员及其下属节点均可见'), (4, '只对指定人、节点可见'), (5, '所有人不可见')], default=1, verbose_name='可见范围类型'),
        ),
        migrations.AlterField(
            model_name='org',
            name='default_app_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_app', to='oneid_meta.AppGroup', verbose_name='App分组默认节点'),
        ),
        migrations.CreateModel(
            name='AppGroupPerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('status', models.IntegerField(choices=[(-1, '显式拒绝'), (0, '随上级决定'), (1, '显式授权')], default=0, verbose_name='授权状态')),
                ('value', models.BooleanField(default=False, verbose_name='是否有权限')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oneid_meta.AppGroup')),
                ('perm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oneid_meta.Perm', verbose_name='权限')),
            ],
            options={
                'abstract': False,
                'unique_together': {('owner', 'perm')},
            },
        ),
        migrations.CreateModel(
            name='AppGroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('order_no', models.IntegerField(default=0, verbose_name='排序号')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oneid_meta.APP')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oneid_meta.AppGroup', verbose_name='所属应用分组')),
            ],
            options={
                'unique_together': {('app', 'owner')},
            },
        ),
    ]
