# Generated by Django 2.2.10 on 2020-05-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0073_crontabplugin_middlewareplugin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deptperm',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='groupperm',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='django_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='userperm',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='unionid',
            field=models.CharField(blank=True, max_length=255, verbose_name='用户OPENID'),
        ),
        migrations.AddIndex(
            model_name='dept',
            index=models.Index(fields=['uid'], name='dept_uid_index'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['uid'], name='group_uid_index'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='username_index'),
        ),
        migrations.AddIndex(
            model_name='wechatuser',
            index=models.Index(fields=['unionid'], name='wechatunionid_index'),
        ),
    ]
