# Generated by Django 2.0.13 on 2020-02-07 17:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0074_customfield_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('order_no', models.IntegerField(default=0, verbose_name='排序号')),
                ('employee_number', models.CharField(blank=True, default='', max_length=255, verbose_name='工号')),
                ('position', models.CharField(blank=True, default='', max_length=255, verbose_name='职位')),
                ('hiredate', models.DateTimeField(blank=True, null=True, verbose_name='入职时间')),
                ('remark', models.CharField(blank=True, default='', max_length=512, verbose_name='备注')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oneid_meta.Org', verbose_name='所属组织')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='employee_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hiredate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='remark',
        ),
        migrations.AddField(
            model_name='orgmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oneid_meta.User'),
        ),
        migrations.AlterUniqueTogether(
            name='orgmember',
            unique_together={('user', 'owner')},
        ),
    ]
