# Generated by Django 2.2.10 on 2020-05-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0074_auto_20200516_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatuser',
            name='unionid',
            field=models.CharField(blank=True, max_length=255, verbose_name='用户OPENID'),
        ),
        migrations.AddIndex(
            model_name='wechatuser',
            index=models.Index(fields=['unionid'], name='wechatunionid_index'),
        ),
    ]
