# Generated by Django 2.2.10 on 2020-06-12 02:42

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0074_auto_20200523_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='data',
            field=django_mysql.models.JSONField(default=dict, verbose_name='信息内容'),
        ),
    ]
