# Generated by Django 2.2.10 on 2021-02-04 09:02

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('oneid_meta', '0080_customgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='subject',
            field=models.CharField(choices=[('user', '内部联系人'), ('extern_user', '外部联系人'), ('node', '组')], default='user', max_length=128, verbose_name='字段分类'),
        ),
        migrations.CreateModel(
            name='CustomDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('data', django_mysql.models.JSONField(default=dict, verbose_name='扩展信息')),
                ('dept', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_dept', to='oneid_meta.Dept', verbose_name='Dept')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
