# Generated by Django 2.2.10 on 2021-07-22 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oneid_meta.models.config
import uuid


def init_contacts_config(apps, schema_editor):

    ContactsConfig = apps.get_model('oneid_meta', 'ContactsConfig')
    Site = apps.get_model('sites', 'Site')

    site, _ = Site.objects.get_or_create(id=settings.SITE_ID)
    ContactsConfig.objects.get_or_create(site=site)


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('oneid_meta', '0082_contactsconfig'),
    ]

    operations = [
        migrations.RunPython(init_contacts_config),
    ]
