package = 'com.longgui.storage.local'
name='本地文件存储'
version='1.1'
labels='storage'
homepage='http://longguikeji.gitee.io/arkid/%20%20%E7%B3%BB%E7%BB%9F%E6%8F%92%E4%BB%B6/com_longgui_storage_local/'
logo=''
author='guancyxx@guancyxx.cn'