TOKEN_URL = 'https://open.feishu.cn/open-apis/auth/v3/app_access_token/internal'
DEPT_CHILD_URL = 'https://open.feishu.cn/open-apis/contact/v3/departments/{}/children?fetch_child={}&page_size={}'
# DEPT_CHILD_ID_URL = 'https://oapi.dingtalk.com/topapi/v2/department/listsubid?access_token={}'
DEPT_URL = 'https://open.feishu.cn/open-apis/contact/v3/departments/{}'
USER_URL = 'https://open.feishu.cn/open-apis/contact/v3/users/find_by_department?department_id={}&page_size={}'
CREATE_DEPT_URL = 'https://open.feishu.cn/open-apis/contact/v3/departments'
CORP_URL = 'https://open.feishu.cn/open-apis/tenant/v2/tenant/query'
EDIT_DEPT_URL = 'https://open.feishu.cn/open-apis/contact/v3/departments/{}'
DELETE_DEPT_URL = 'https://open.feishu.cn/open-apis/contact/v3/departments/{}'
CREATE_USER_URL = 'https://open.feishu.cn/open-apis/contact/v3/users'
UPDATE_USER_URL = 'https://open.feishu.cn/open-apis/contact/v3/users/{}'
USER_MOBILE_URL = 'https://open.feishu.cn/open-apis/contact/v3/users/batch_get_id'
GET_USER_URL = 'https://open.feishu.cn/open-apis/contact/v3/users/{}'