# Generated by Django 3.2.6 on 2021-09-03 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_systemprivacynotice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemPrivacyNotice',
        ),
    ]
