## 用来开发的镜像，devops/docker-compose/docker-compose.yml
## docker build -t arkid-dev . -f Dockerfile-for-dev
FROM registry.cn-hangzhou.aliyuncs.com/newbe36524/vscode_python:0-3.6
COPY *.txt ./
COPY uwsgi.ini /etc/uwsgi/uwsgi.ini
COPY devops/pip.conf /root/.pip/pip.conf

RUN sed -i "s@http://deb.debian.org/debian@http://mirrors.aliyun.com/debian/@g" /etc/apt/sources.list &&\
    sed -i "s@http://security.debian.org/debian-security@http://mirrors.aliyun.com/debian-security@g" /etc/apt/sources.list &&\
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - &&\
    apt-get update &&\
    apt-get install -y --no-install-recommends \
        vim supervisor gettext xmlsec1 \
        python-dev default-libmysqlclient-dev &&\
    pip install uwsgi mysqlclient==1.4.6 &&\
    pip install -r requirements.txt &&\
    pip install -r requirements-dev.txt
