package = "com.longgui.language.en"
name='English Language Package'
version='1.0'
labels='English'
homepage='http://longguikeji.gitee.io/arkid/%20%20%E7%B3%BB%E7%BB%9F%E6%8F%92%E4%BB%B6/com_longgui_language_en/'
logo=''
author='guancyxx@guancyxx.cn'