    package='com.longgui.sms.aliyun'
    name='阿里云短信'
    version='1.0'
    labels='aliyun'
    homepage='http://longguikeji.gitee.io/arkid/%20%20%E7%B3%BB%E7%BB%9F%E6%8F%92%E4%BB%B6/com_longgui_sms_aliyun/'
    logo=''
    author='hanbin@jinji-inc.com'