# Generated by Django 3.2 on 2021-05-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='password',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
