# Generated by Django 3.2.4 on 2021-06-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0002_auto_20210521_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='endpoint',
            new_name='base_url',
        ),
        migrations.RemoveField(
            model_name='config',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='config',
            name='schemas',
        ),
        migrations.AddField(
            model_name='config',
            name='auth_type',
            field=models.CharField(choices=[(0, 'Basic Auth'), (1, 'Token Auth')], default=1, max_length=32),
        ),
        migrations.AddField(
            model_name='config',
            name='sync_type',
            field=models.CharField(choices=[(0, 'Upstream'), (1, 'Downstream')], default=1, max_length=32),
        ),
    ]
