# Generated by Django 3.2 on 2021-07-02 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0003_auto_20210614_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='auth_type',
            field=models.IntegerField(choices=[(0, 'Basic Auth'), (1, 'Token Auth')], default=1, max_length=32),
        ),
        migrations.AlterField(
            model_name='config',
            name='sync_type',
            field=models.IntegerField(choices=[(0, 'Upstream'), (1, 'Downstream')], default=1, max_length=32),
        ),
    ]
