# Generated by Django 3.2.6 on 2021-08-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0005_auto_20210811_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='auth_type',
            field=models.CharField(choices=[('basic', 'Basic Auth'), ('token', 'Token Auth')], default='token', max_length=32),
        ),
        migrations.AlterField(
            model_name='config',
            name='status',
            field=models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='disabled', max_length=32),
        ),
        migrations.AlterField(
            model_name='config',
            name='sync_type',
            field=models.CharField(choices=[('upstream', 'Upstream'), ('downstream', 'Downstream')], default='downstream', max_length=32),
        ),
    ]
