# Generated by Django 3.2 on 2021-04-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0005_auto_20210217_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idtoken',
            name='token',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
