# Generated by Django 3.2 on 2021-06-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0006_alter_idtoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='custom_template',
            field=models.TextField(blank=True, help_text='Application custom authorization html page'),
        ),
    ]
