# Generated by Django 3.2.8 on 2022-01-12 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0030_merge_20210930_0611'),
        ('oauth2_provider', '0008_auto_20220112_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='tenant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenant.tenant'),
        ),
    ]
