# Generated by Django 3.2.8 on 2022-02-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0009_grant_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idtoken',
            name='token',
            field=models.TextField(),
        ),
    ]
