# Generated by Django 2.0.13 on 2020-04-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0009_auto_20200407_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcgrant',
            name='code_challenge',
            field=models.CharField(max_length=255, null=True, verbose_name='Code Challenge'),
        ),
        migrations.AddField(
            model_name='oidcgrant',
            name='code_challenge_method',
            field=models.CharField(choices=[('plain', 'plain coded format'), ('S256', 'S256 coded format')], max_length=255, null=True, verbose_name='Code Challenge Method'),
        ),
        migrations.AddField(
            model_name='oidcgrant',
            name='nonce',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nonce'),
        ),
    ]
