# Generated by Django 3.2.13 on 2022-05-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0012_auto_20220520_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='uuid',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
