package='com.longgui.app.protocol.oidc'
name='OIDC&OAuth2认证协议'
version='1.0'
labels=['OAuth2','OIDC']
homepage='http://longguikeji.gitee.io/arkid/%20%20%E7%B3%BB%E7%BB%9F%E6%8F%92%E4%BB%B6/com_longgui_app_protocol_oidc/OIDC/'
logo=''
author='hanbin@jinji-inc.com'