package='com.longgui.auth.factor.ldap'
name='LDAP认证因素'
version='1.2'
labels=['ldap', 'auth_factor']
homepage='http://longguikeji.gitee.io/arkid/%20%E5%85%B6%E5%AE%83%E6%8F%92%E4%BB%B6/com_longgui_auth_factor_ldap/'
logo=''
author='guancyxx@guancyxx.cn'