# Generated by Django 3.1.5 on 2021-01-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_auto_20210117_0933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebHookSendHistory',
            new_name='WebHookTriggerHistory',
        ),
    ]
