# Generated by Django 3.1.5 on 2021-01-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_auto_20210117_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhooktriggerhistory',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='webhooktriggerhistory',
            name='webhook',
        ),
        migrations.DeleteModel(
            name='WebHook',
        ),
        migrations.DeleteModel(
            name='WebHookTriggerHistory',
        ),
    ]
