# Generated by Django 3.1.6 on 2021-02-20 12:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_auto_20210121_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='icon',
            field=models.URLField(blank=True, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=128, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(verbose_name='短链接标识'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID'),
        ),
    ]
