# Generated by Django 3.2 on 2021-06-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0008_tenantpasswordcomplexity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantpasswordcomplexity',
            name='title',
            field=models.CharField(default='', max_length=128, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='tenantpasswordcomplexity',
            name='regular',
            field=models.CharField(max_length=512, verbose_name='正则表达式'),
        ),
    ]
