# Generated by Django 3.2 on 2021-06-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0010_add_regular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantpasswordcomplexity',
            name='title',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='标题'),
        ),
    ]
