# Generated by Django 3.2.5 on 2021-08-03 07:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0013_add_tenantcontactsconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantcontactsconfig',
            name='config_type',
            field=models.IntegerField(choices=[(0, '功能开关'), (1, '分组可见性')], default=0, verbose_name='配置类型'),
        ),
        migrations.CreateModel(
            name='TenantContactsUserFieldConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='字段名称')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenant.tenant', verbose_name='租户')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
