# Generated by Django 3.2.6 on 2021-08-06 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0012_tenantprivacynotice'),
        ('tenant', '0015_add_tenantcontactsuserfieldconfig'),
    ]

    operations = [
    ]
