# Generated by Django 3.2.6 on 2021-08-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0017_tenantdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantdevice',
            name='device_type',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='设备类型'),
        ),
    ]
