# Generated by Django 3.2.6 on 2021-08-17 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0018_alter_tenantdevice_device_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TenantDevice',
        ),
    ]
