# Generated by Django 3.2.6 on 2021-08-18 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0019_delete_tenantdevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantcontactsconfig',
            name='config_type',
        ),
    ]
