# Generated by Django 3.2.5 on 2021-09-23 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0025_tenant_use_slug'),
        ('tenant', '0025_tenantlogconfig'),
    ]

    operations = [
    ]
