# Generated by Django 3.1.7 on 2021-03-28 14:03

from django.db import migrations


def add_switch(apps, schema_editor):
    pass
    # from tenant.models import Tenant, TenantSwitch
    # default_tenant = Tenant.objects.filter(id=1).first()
    # if default_tenant:
    #     tenant_switch = TenantSwitch.active_objects.first()
    #     if not tenant_switch:
    #         tenant_switch = TenantSwitch()
    #         tenant_switch.tenant = default_tenant
    #         tenant_switch.switch = True
    #         tenant_switch.save()



class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0027_tenantswitch'),
    ]

    operations = [
        migrations.RunPython(add_switch),
    ]
