# Generated by Django 3.1.7 on 2021-03-28 14:03

from django.db import migrations


def add_switch(apps, schema_editor):
    from tenant.models import Tenant
    default_tenant = Tenant.objects.filter(id=1).first()
    if default_tenant:
        default_tenant.slug = ''
        default_tenant.name = 'platform tenant'
        default_tenant.save()



class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0028_add_tenant_switch'),
    ]

    operations = [
        migrations.RunPython(add_switch),
    ]
