# Generated by Django 3.2.5 on 2021-09-30 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0026_merge_0025_tenant_use_slug_0025_tenantlogconfig'),
        ('tenant', '0029_update_tenant_slug'),
    ]

    operations = [
    ]
