# Generated by Django 3.2.10 on 2021-12-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0030_merge_20210930_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='background_url',
            field=models.URLField(blank=True, verbose_name='登录页背景图片'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='copyright_text',
            field=models.CharField(blank=True, max_length=128, verbose_name='登录页版权文字'),
        ),
    ]
