# Generated by Django 3.1.7 on 2021-03-28 14:03

from django.db import migrations


def add_default_tenant_config(apps, schema_editor):
    # from tenant.models import TenantConfig, Tenant

    # tenant = Tenant.objects.filter(id=1).first()
    # TenantConfig.objects.get_or_create(
    #     tenant=tenant,
    #     data={
    #         "is_open_register_limit": False,
    #         "register_time_limit": 1,
    #         "register_count_limit": 10,
    #         "upload_file_format": ["jpg", "png", "gif", "jpeg"],
    #         "close_page_auto_logout": False,
    #         "password_validity_period": 60,
    #     },
    # )
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0031_auto_20211231_0851'),
    ]

    operations = [
        migrations.RunPython(add_default_tenant_config),
    ]
