package='com.longgui.export.user'
name='用户和分组导入导出'
version='1.4'
labels='export_user'
homepage='http://longguikeji.gitee.io/arkid/%20%E5%85%B6%E5%AE%83%E6%8F%92%E4%BB%B6/com_longgui_export_user/'
logo=''
author='hanbin@jinji-inc.com'