package = "com.longgui.auth.factor.password"
name="密码认证因素"
version='1.0'
labels='auth_factor'
homepage='http://longguikeji.gitee.io/arkid/%20%20%E7%B3%BB%E7%BB%9F%E6%8F%92%E4%BB%B6/com_longgui_auth_factor_password/'
logo=''
author='wely@longguikeji.com'