# Generated by Django 3.1.7 on 2021-03-25 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0002_auto_20210325_0911'),
        ('github', '0002_auto_20210317_0133'),
    ]

    operations = [
    ]
