# Generated by Django 3.1.7 on 2021-03-25 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0003_merge_20210325_1208'),
        ('github', '0003_merge_20210325_1047'),
    ]

    operations = [
    ]
