package = 'com.longgui.authrule.blacklist'
name='账号黑名单认证规则'
version='1.0'
labels='auth_rule'
homepage='http://longguikeji.gitee.io/arkid/%20%20%E7%B3%BB%E7%BB%9F%E6%8F%92%E4%BB%B6/com_longgui_auth_rule_black_list/'
logo=''
author='guancyxx@guancyxx.cn'