# Generated by Django 3.2.13 on 2022-05-19 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220519_1357'),
        ('com_longgui_mobile_auth_factor', '0002_auto_20220519_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermobile',
            name='target',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='com_longgui_mobile_auth_factor_UserMobile', to='core.user'),
        ),
    ]
