package='com.longgui.app.protocol.cas.server'
name='CAS认证协议'
version='1.0'
labels=['CAS']
homepage='http://longguikeji.gitee.io/arkid/%20%E5%85%B6%E5%AE%83%E6%8F%92%E4%BB%B6/com_longgui_app_protocol_cas_server/'
logo=''
author='hanbin@jinji-inc.com'