package = 'com.longgui.scim.sync.ad'
name='AD用户数据同步'
version='1.1'
labels='LDAP'
homepage='http://longguikeji.gitee.io/arkid/%20%E5%85%B6%E5%AE%83%E6%8F%92%E4%BB%B6/com_longgui_scim_sync_ad/'
logo=''
author='fanhe@longguikeji.com'
