package = "com.longgui.auth.factor.mobile"
name="手机验证码认证因素"
version='1.0'
labels='mobile'
homepage='http://longguikeji.gitee.io/arkid/%20%20%E7%B3%BB%E7%BB%9F%E6%8F%92%E4%BB%B6/com_longgui_auth_factor_mobile/'
logo=''
author='guancyxx@guancyxx.cn'