# Generated by Django 3.2.13 on 2022-05-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhookevent',
            name='webhook',
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='webhooks',
            field=models.ManyToManyField(blank=True, related_name='events_set', related_query_name='events', to='webhook.Webhook'),
        ),
    ]
