# Generated by Django 3.2 on 2021-05-14 08:35

from django.db import migrations, models
import jsonfield.fields
import webhook.models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0002_auto_20210220_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='secret',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='webhooktriggerhistory',
            name='request',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='webhooktriggerhistory',
            name='response',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
