# Generated by Django 3.2.13 on 2022-05-19 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0002_auto_20220518_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhooktriggerhistory',
            name='webhook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_set', related_query_name='histories', to='webhook.webhook'),
        ),
    ]
