# Generated by Django 3.2.5 on 2021-07-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0003_auto_20210514_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhooktriggerhistory',
            name='request',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='webhooktriggerhistory',
            name='response',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='webhooktriggerhistory',
            name='status',
            field=models.CharField(choices=[('waiting', '等待发送'), ('success', '发送成功'), ('failed', '发送异常')], default='waiting', max_length=128),
        ),
    ]
