# Generated by Django 3.2.13 on 2022-05-19 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0003_alter_webhooktriggerhistory_webhook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhooktriggerhistory',
            name='Http返回结果',
        ),
    ]
