# Generated by Django 3.2.5 on 2021-07-22 11:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0004_auto_20210714_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhook',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='webhook',
            name='events',
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('event_type', models.CharField(db_index=True, max_length=128, verbose_name='Event type')),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='webhook.webhook')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
