# Generated by Django 3.2.13 on 2022-05-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0004_remove_webhooktriggerhistory_http返回结果'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooktriggerhistory',
            name='response',
            field=models.JSONField(blank=True, default=dict, verbose_name='Http Response'),
        ),
    ]
