# Generated by Django 3.2.13 on 2022-05-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0005_webhooktriggerhistory_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhooktriggerhistory',
            name='request',
            field=models.TextField(blank=True, null=True, verbose_name='Http Request'),
        ),
        migrations.AlterField(
            model_name='webhooktriggerhistory',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='Http Response'),
        ),
    ]
