package = 'com.longgui.external.idp.wechatwork'
name='企业微信授权登录'
version='1.2'
labels='wechatwork'
homepage='http://longguikeji.gitee.io/arkid/%20%E5%85%B6%E5%AE%83%E6%8F%92%E4%BB%B6/com_longgui_external_idp_wechatwork/'
logo=''
author='fanhe@longguikeji.com'
