# Generated by Django 3.2.7 on 2021-11-01 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_app_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSubscribeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscribed_record', to='app.app', verbose_name='应用')),
                ('users', models.ManyToManyField(related_name='app_subscribed_records', to=settings.AUTH_USER_MODEL, verbose_name='订阅用户')),
            ],
            options={
                'verbose_name': '应用订阅记录',
            },
        ),
    ]
