# Generated by Django 3.2.7 on 2021-11-26 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_market_manage', '0002_appsubscriberecord_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsubscriberecord',
            name='tenant',
        ),
    ]
