# Generated by Django 3.1.6 on 2021-03-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='type',
            field=models.CharField(default='', max_length=128, verbose_name='App Type'),
            preserve_default=False,
        ),
    ]
