# Generated by Django 3.1.7 on 2021-03-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_app_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='data',
            field=models.JSONField(blank=True, default={}),
        ),
    ]
