# Generated by Django 3.1.7 on 2021-03-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210326_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
