# Generated by Django 3.2.6 on 2021-09-15 03:31

from django.db import migrations, models
import oauth2_provider.generators


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_app_auth_tmpl'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='token',
            field=models.CharField(blank=True, default=oauth2_provider.generators.generate_client_secret, max_length=255, null=True),
        ),
    ]
