package='com.longgui.other.app.subscribe'
name='应用订阅管理插件'
version='1.0'
labels=['other',"app_subscribe","global"]
homepage='http://longguikeji.gitee.io/arkid/%20%E5%85%B6%E5%AE%83%E6%8F%92%E4%BB%B6/com_longgui_other_app_subscribe/'
logo=''
author='guancyxx@guancyxx.cn'