# Generated by Django 4.0.6 on 2022-09-02 11:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_apppermissionresult'),
        ('com_longgui_logging_mysql', '0002_alter_log_tenant_alter_log_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantLogConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('log_retention_period', models.IntegerField(blank=True, default=30, verbose_name='日志保存天数')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.tenant', verbose_name='租户')),
            ],
        ),
    ]
