package='com.longgui.account.life.arkid'
name='默认账号生命周期管理'
version='1.0'
labels='arkid'
homepage='http://longguikeji.gitee.io/arkid/%20%20%E7%B3%BB%E7%BB%9F%E6%8F%92%E4%BB%B6/com_longgui_account_life_arkid/'
logo=''
author='fanhe@longguikeji.com'
