package='com.longgui.auto.password'
name="账号自动生成密码插件"
version='1.0'
labels='auto password'
homepage='http://longguikeji.gitee.io/arkid/%20%E5%85%B6%E5%AE%83%E6%8F%92%E4%BB%B6/com_longgui_auto_password/'
logo=''
author='guancyxx@guancyxx.cn'
