package='com.longgui.message.artemis'
name='消息中间件：Artemis'
version='1.0'
labels=['other',"message","artemis"]
homepage='http://longguikeji.gitee.io/arkid/%20%E5%85%B6%E5%AE%83%E6%8F%92%E4%BB%B6/com_longgui_message_artemis/'
logo=''
author='guancyxx@guancyxx.cn'