# Generated by Django 3.1.7 on 2021-03-31 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_idp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalidp',
            name='order_no',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
