# Generated by Django 4.0.3 on 2022-04-13 10:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('labels', models.CharField(max_length=128, verbose_name='标签')),
                ('package', models.CharField(max_length=128, verbose_name='标识')),
                ('ext_dir', models.CharField(max_length=1024, verbose_name='完整路径名')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('version', models.CharField(max_length=128, verbose_name='版本')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否启用')),
                ('is_allow_use_platform_config', models.BooleanField(default=False, verbose_name='是否允许租户启用平台配置')),
            ],
            options={
                'verbose_name': '插件',
                'verbose_name_plural': '插件',
                'unique_together': {('package', 'version')},
            },
        ),
        migrations.CreateModel(
            name='TenantExtensionConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='配置')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='extension.extension', verbose_name='插件')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '租户插件配置',
                'verbose_name_plural': '租户插件配置',
            },
        ),
        migrations.CreateModel(
            name='TenantExtension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否启用')),
                ('use_platform_config', models.BooleanField(default=False, verbose_name='是否启用平台配置')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='extension.extension', verbose_name='插件')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tenant', verbose_name='租户')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
