# Generated by Django 4.0.3 on 2022-04-01 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='extension',
            unique_together={('package', 'version')},
        ),
    ]
