# Generated by Django 4.0.4 on 2022-04-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='extension',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='extension',
            name='package',
            field=models.CharField(max_length=128, unique=True, verbose_name='标识'),
        ),
    ]
