# Generated by Django 4.0.3 on 2022-04-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0002_alter_extension_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='ext_dir',
            field=models.CharField(default='', max_length=1024, verbose_name='完整路径名'),
            preserve_default=False,
        ),
    ]
