# Generated by Django 3.2.13 on 2022-06-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0002_remove_tenantextension_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='labels',
            field=models.JSONField(blank=True, default=[], verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='profile',
            field=models.JSONField(blank=True, default={}, verbose_name='Setup Profile'),
        ),
    ]
