# Generated by Django 4.0.4 on 2022-04-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('extension', '0002_alter_tenantextension_options_extension_profile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantextension',
            options={'verbose_name': '插件租户配置', 'verbose_name_plural': '插件租户配置'},
        ),
        migrations.AlterModelOptions(
            name='tenantextensionconfig',
            options={'verbose_name': '插件运行时配置', 'verbose_name_plural': '插件运行时配置'},
        ),
        migrations.AlterField(
            model_name='extension',
            name='package',
            field=models.CharField(db_index=True, max_length=128, unique=True, verbose_name='标识'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantextension',
            unique_together={('tenant', 'extension')},
        ),
    ]
