# Generated by Django 4.0.4 on 2022-04-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0002_alter_extension_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='type',
            field=models.CharField(default='base', max_length=64, verbose_name='类型'),
        ),
    ]
