# Generated by Django 3.2.13 on 2022-06-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0003_auto_20220602_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='labels',
            field=models.JSONField(blank=True, default=[], verbose_name='Labels'),
        ),
    ]
