# Generated by Django 3.2.13 on 2022-06-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0003_auto_20220602_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='labels',
            field=models.JSONField(blank=True, default=list, verbose_name='Labels'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='profile',
            field=models.JSONField(blank=True, default=dict, verbose_name='Setup Profile'),
        ),
    ]
