# Generated by Django 4.0.4 on 2022-04-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0003_alter_tenantextension_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantextensionconfig',
            name='type',
            field=models.CharField(default='', max_length=128, verbose_name='类型'),
        ),
    ]
