# Generated by Django 3.2.13 on 2022-05-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0004_tenantextensionconfig_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantextension',
            name='type',
            field=models.CharField(default='', max_length=128, verbose_name='类型'),
        ),
    ]
