# Generated by Django 3.2.13 on 2022-06-14 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0004_alter_extension_labels'),
        ('extension', '0004_auto_20220602_1325'),
    ]

    operations = [
    ]
