# Generated by Django 3.2.13 on 2022-06-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0007_alter_extension_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantextension',
            name='is_rented',
            field=models.BooleanField(default=False, verbose_name='是否已租赁'),
        ),
    ]
