# Generated by Django 4.0.6 on 2022-10-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0010_arkstorecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='author',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='extension',
            name='homepage',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='extension',
            name='logo',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
