# Generated by Django 4.0.6 on 2022-10-21 01:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0030_userpersonalsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWebauthnCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('credential_id', models.CharField(max_length=256, verbose_name='Credential ID')),
                ('credential', models.JSONField(blank=True, default=dict, verbose_name='Credential')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credential_set', related_query_name='webauthn_credentials', to='core.user', verbose_name='User')),
            ],
        ),
    ]
