# Generated by Django 4.0.7 on 2022-11-08 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_expiringtoken_active_date'),
        ('com_longgui_default_desktop', '0002_alter_defaultdesktop_default_desktop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultdesktop',
            name='target',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='core.tenant'),
        ),
    ]
