# Generated by Django 3.2.6 on 2021-08-17 07:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('device_type', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='设备类型')),
                ('system_version', models.CharField(blank=True, default='', max_length=216, null=True, verbose_name='操作系统及版本')),
                ('browser_version', models.CharField(blank=True, default='', max_length=216, null=True, verbose_name='浏览器及版本')),
                ('ip', models.CharField(blank=True, default='', max_length=216, null=True, verbose_name='IP地址')),
                ('mac_address', models.CharField(blank=True, default='', max_length=216, null=True, verbose_name='mac地址')),
                ('device_number', models.CharField(blank=True, default='', max_length=216, null=True, verbose_name='设备号')),
                ('device_id', models.CharField(blank=True, default='', max_length=216, null=True, verbose_name='设备编号')),
                ('account_ids', models.JSONField(blank=True, default=dict, verbose_name='用户账号ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
