package='com.longgui.system.doc'
name="验收文档"
version='1.0'
labels='systemdoc'
homepage='http://longguikeji.gitee.io/arkid/%20%E5%85%B6%E5%AE%83%E6%8F%92%E4%BB%B6/com_longgui_system_doc/'
logo=''
author='hanbin@jinji-inc.com'
