# Generated by Django 3.2.7 on 2021-11-07 11:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0007_app_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationMultipleIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('ip_regx', models.CharField(max_length=200, verbose_name='网段正则表达式')),
                ('ip', models.GenericIPAddressField(verbose_name='IP地址')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='multiple_ips', to='app.app', verbose_name='应用')),
            ],
            options={
                'verbose_name_plural': '应用多网段IP地址对应表',
            },
        ),
    ]
