# Generated by Django 3.2 on 2021-04-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='group',
            name='scim_display_name',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='A human-readable name for the Group.', max_length=254, null=True, verbose_name='SCIM Display Name'),
        ),
        migrations.AddField(
            model_name='group',
            name='scim_external_id',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='A string that is an identifier for the resource as defined by the provisioning client.', max_length=254, null=True, verbose_name='SCIM External ID'),
        ),
        migrations.AddField(
            model_name='group',
            name='scim_id',
            field=models.CharField(blank=True, default=None, help_text='A unique identifier for a SCIM resource as defined by the service provider.', max_length=254, null=True, unique=True, verbose_name='SCIM ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='scim_external_id',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='A string that is an identifier for the resource as defined by the provisioning client.', max_length=254, null=True, verbose_name='SCIM External ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='scim_id',
            field=models.CharField(blank=True, default=None, help_text='A unique identifier for a SCIM resource as defined by the service provider.', max_length=254, null=True, unique=True, verbose_name='SCIM ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='scim_username',
            field=models.CharField(blank=True, db_index=True, default=None, help_text="A service provider's unique identifier for the user", max_length=254, null=True, verbose_name='SCIM Username'),
        ),
    ]
