# Generated by Django 3.2.4 on 2021-06-15 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20210427_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=128, verbose_name='字段名称')),
                ('subject', models.CharField(choices=[('user', '内部联系人'), ('extern_user', '外部联系人'), ('node', '组')], default='user', max_length=128, verbose_name='字段分类')),
                ('schema', models.JSONField(default={'type': 'string'}, verbose_name='字段定义')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否展示')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NativeField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=128, verbose_name='字段名称')),
                ('key', models.CharField(max_length=256, verbose_name='内部字段名')),
                ('subject', models.CharField(choices=[('user', '内部联系人'), ('extern_user', '外部联系人')], default='user', max_length=128, verbose_name='字段分类')),
                ('schema', models.JSONField(default={'type': 'string'}, verbose_name='字段定义')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否展示')),
                ('is_visible_editable', models.BooleanField(default=True, verbose_name='对于`是否展示`，是否可以修改')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('data', models.JSONField(verbose_name='信息内容')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_user', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
