# Generated by Django 3.2 on 2021-06-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_userpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_platform_user',
            field=models.BooleanField(default=False, verbose_name='是否是平台用户'),
        ),
    ]
