# Generated by Django 3.2.4 on 2021-06-15 07:31

from django.db import migrations
from django.conf import settings

def init_user_native_field(apps, schema_editor):
    '''
    补充初始化字段
    '''
    if settings.TESTING:
        return None
    NativeField = apps.get_model('inventory', 'NativeField')
    subject = 'user'

    NativeField.objects.create(subject=subject, name='名字', key='first_name', schema={'type': 'string'})
    NativeField.objects.create(subject=subject, name='姓氏', key='last_name', schema={'type': 'string'})
    NativeField.objects.create(subject=subject, name='昵称', key='nickname', schema={'type': 'string'})
    NativeField.objects.create(subject=subject, name='手机号', key='mobile', schema={'type': 'string'})
    NativeField.objects.create(subject=subject, name='邮箱', key='email', schema={'type': 'string'})
    NativeField.objects.create(subject=subject, name='国家', key='country', schema={'type': 'string'})
    NativeField.objects.create(subject=subject, name='城市', key='city', schema={'type': 'string'})
    NativeField.objects.create(subject=subject, name='职位', key='job_title', schema={'type': 'string'})

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_customfield_customuser_nativefield'),
    ]

    operations = [
        migrations.RunPython(init_user_native_field),
    ]
