# Generated by Django 3.2.5 on 2021-07-13 11:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='I18NMobileConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('state', models.CharField(max_length=128, unique=True, verbose_name='号码归属区域')),
                ('state_code', models.CharField(max_length=32, unique=True, verbose_name='国家区号')),
                ('number_length', models.IntegerField(default=None, null=True, verbose_name='号码固定长度')),
                ('start_digital', models.JSONField(blank=True, default=[], verbose_name='首位数字限制集')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
