# Generated by Django 3.2.4 on 2021-06-15 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_auto_20210220_1237'),
        ('inventory', '0012_auto_20210615_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tenant.tenant'),
        ),
    ]
