# Generated by Django 3.2.5 on 2021-07-14 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_customfield_tenant'),
        ('inventory', '0013_i18nmobileconfig'),
    ]

    operations = [
    ]
