# Generated by Django 3.2.4 on 2021-07-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_user_is_platform_user'),
        ('inventory', '0013_customfield_tenant'),
    ]

    operations = [
    ]
