# Generated by Django 3.2.6 on 2021-08-20 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20210811_0922'),
        ('inventory', '0015_userappdata'),
    ]

    operations = [
    ]
