# Generated by Django 3.2.6 on 2021-08-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20210811_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='subject',
            field=models.CharField(choices=[('user', '用户'), ('group', '组')], default='user', max_length=128, verbose_name='字段分类'),
        ),
    ]
