# Generated by Django 3.2.6 on 2021-08-23 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_customfield_subject'),
        ('inventory', '0016_merge_0015_auto_20210811_0922_0015_userappdata'),
    ]

    operations = [
    ]
