# Generated by Django 3.2.6 on 2021-09-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_user_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='is_system_permission',
            field=models.BooleanField(default=True, verbose_name='是否是系统权限'),
        ),
        migrations.AddField(
            model_name='permission',
            name='permission_type',
            field=models.IntegerField(choices=[(0, '未知'), (1, '入口'), (2, 'API'), (3, '数据')], default=0, verbose_name='权限类型'),
        ),
    ]
