# Generated by Django 3.2.6 on 2021-09-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_user_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_update_pwd',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
