# Generated by Django 3.2.6 on 2021-09-10 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_app_auth_tmpl'),
        ('inventory', '0019_auto_20210909_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='app',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.app'),
        ),
    ]
