# Generated by Django 3.2.6 on 2021-09-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_permission_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='permission_type',
        ),
        migrations.AddField(
            model_name='permission',
            name='permission_category',
            field=models.CharField(default='', max_length=64, null=True, verbose_name='权限类型'),
        ),
    ]
