# Generated by Django 3.2.6 on 2021-09-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_permissiongroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiongroup',
            name='is_system_group',
            field=models.BooleanField(default=True, verbose_name='是否是系统权限'),
        ),
    ]
