# Generated by Django 3.2.6 on 2021-09-14 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0024_auto_20210903_0422'),
        ('inventory', '0023_permissiongroup_is_system_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiongroup',
            name='tenant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenant.tenant'),
        ),
    ]
