# Generated by Django 3.2.6 on 2021-09-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_permissiongroup_tenant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissiongroup',
            old_name='permission',
            new_name='permissions',
        ),
    ]
