# Generated by Django 3.2.6 on 2021-09-22 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_user_last_update_pwd'),
        ('inventory', '0028_add_default_permission'),
    ]

    operations = [
    ]
