# Generated by Django 3.2.10 on 2022-02-17 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_auto_20220216_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='request_type',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='请求方法'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='permission_parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.permissiongroup', verbose_name='父分组'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='动作'),
        ),
    ]
