# Generated by Django 3.2.10 on 2022-02-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_permissiongroup_is_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiongroup',
            name='en_name',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='en_name'),
        ),
    ]
