# Generated by Django 3.2.10 on 2022-02-23 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0032_add_default_tenant_config'),
        ('inventory', '0038_permissiongroup_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='group_info',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.group', verbose_name='分组'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='tenant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='permissiongroup',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.permissiongroup', verbose_name='父分组'),
        ),
        migrations.AlterField(
            model_name='permissiongroup',
            name='tenant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
    ]
