# Generated by Django 3.2.10 on 2022-03-02 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenant', '0032_add_default_tenant_config'),
        ('inventory', '0041_usertenantpermissiongroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTenantPermissionAndPermissionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('permission', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.permission', verbose_name='权限')),
                ('permissiongroup', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.permissiongroup', verbose_name='权限组')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tenant.tenant', verbose_name='租户')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.DeleteModel(
            name='UserTenantPermissionGroup',
        ),
        migrations.AddField(
            model_name='usertenantpermissionandpermissiongroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_user', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
