# Generated by Django 3.2.10 on 2022-03-02 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_auto_20220302_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='group_info',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.group', verbose_name='分组'),
        ),
    ]
