# Generated by Django 3.2.10 on 2022-03-18 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0032_add_default_tenant_config'),
        ('inventory', '0046_usermenudata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappdata',
            name='tenant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenant.tenant', verbose_name='租户'),
        ),
    ]
