# Generated by Django 3.2.10 on 2022-03-21 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0032_add_default_tenant_config'),
        ('inventory', '0049_permissiongroup_base_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertenantpermissionandpermissiongroup',
            name='permission',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.permission', verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='usertenantpermissionandpermissiongroup',
            name='permissiongroup',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.permissiongroup', verbose_name='权限组'),
        ),
        migrations.AlterField(
            model_name='usertenantpermissionandpermissiongroup',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant', verbose_name='租户'),
        ),
    ]
