# Generated by Django 3.2.10 on 2022-03-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0053_permissiongroup_app'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='parents',
            new_name='container',
        ),
        migrations.RenameField(
            model_name='permissiongroup',
            old_name='parents',
            new_name='container',
        ),
        migrations.AddField(
            model_name='permission',
            name='parent_sort_id',
            field=models.IntegerField(default=-1, verbose_name='parent_sort_id'),
        ),
        migrations.AddField(
            model_name='permissiongroup',
            name='parent_sort_id',
            field=models.IntegerField(default=-1, verbose_name='parent_sort_id'),
        ),
    ]
