# Generated by Django 3.2.10 on 2022-03-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0054_auto_20220329_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapppermissionresult',
            name='is_update',
            field=models.BooleanField(default=False, verbose_name='是否更新'),
        ),
    ]
