# Generated by Django 3.2.10 on 2022-04-13 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0055_userapppermissionresult_is_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpassword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
