package='com.longgui.cache.redis'
name='缓存插件:Redis'
version='1.0'
labels=['cache',"redis","tenant"]
homepage='http://longguikeji.gitee.io/arkid/%20%E5%85%B6%E5%AE%83%E6%8F%92%E4%BB%B6/com_longgui_cache_redis/'
logo=''
author='guancyxx@guancyxx.cn'