# Generated by Django 3.2.13 on 2022-08-11 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0020_platform_frontend_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSubscribeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_records', to='core.app')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_subscribe_records', to='core.user')),
            ],
        ),
    ]
