# Generated by Django 3.2.6 on 2021-09-03 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0024_auto_20210903_0422'),
        ('config', '0002_alter_passwordcomplexity_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacynotice',
            name='tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='privacy_notice', to='tenant.tenant', verbose_name='租户'),
        ),
    ]
