TOKEN_URL = 'https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid={}&corpsecret={}'
# DEPT_CHILD_URL = 'https://open.feishu.cn/open-apis/contact/v3/departments/{}/children?fetch_child={}&page_size={}'
# DEPT_CHILD_ID_URL = 'https://oapi.dingtalk.com/topapi/v2/department/listsubid?access_token={}'
DEPT_URL = 'https://qyapi.weixin.qq.com/cgi-bin/department/list?access_token={}'
USER_URL = 'https://qyapi.weixin.qq.com/cgi-bin/user/list?access_token={}&department_id={}'
CREATE_DEPT_URL = 'https://qyapi.weixin.qq.com/cgi-bin/department/create?access_token={}'
# CORP_URL = 'https://open.feishu.cn/open-apis/tenant/v2/tenant/query'
# EDIT_DEPT_URL = 'https://open.feishu.cn/open-apis/contact/v3/departments/{}'
DELETE_DEPT_URL = 'https://qyapi.weixin.qq.com/cgi-bin/department/delete?access_token={}&id={}'
CREATE_USER_URL = 'https://qyapi.weixin.qq.com/cgi-bin/user/create?access_token={}'
UPDATE_USER_URL = 'https://qyapi.weixin.qq.com/cgi-bin/user/update?access_token={}'
USER_MOBILE_URL = 'https://qyapi.weixin.qq.com/cgi-bin/user/getuserid?access_token={}'
GET_USER_URL = 'https://qyapi.weixin.qq.com/cgi-bin/user/get?access_token={}&userid={}'