package = 'com.longgui.scim.sync.wechatwork'
name='企业微信数据同步'
version='1.0'
labels='scim sync'
homepage='http://longguikeji.gitee.io/arkid/%20%E5%85%B6%E5%AE%83%E6%8F%92%E4%BB%B6/com_longgui_scim_sync_wechatwork/'
logo=''
author='hanbin@longguikeji.com'
