package='com.longgui.custom.field'
name="自定义字段插件"
version='1.1'
labels='field'
homepage='http://longguikeji.gitee.io/arkid/%20%E5%85%B6%E5%AE%83%E6%8F%92%E4%BB%B6/com_longgui_custom_field/'
logo=''
author='case@company.com'
