package = 'com.longgui.external.idp.dingding'
name='钉钉第三方登录服务'
version='1.1'
labels='dingding'
homepage='http://longguikeji.gitee.io/arkid/%20%E5%85%B6%E5%AE%83%E6%8F%92%E4%BB%B6/com_longgui_external_idp_dingding/'
logo=''
author='fanhe@longguikeji.com'
