package = 'com.longgui.external.idp.wechatscan'
name='微信扫码登录服务'
version='1.1'
labels='wechatscan'
homepage='http://longguikeji.gitee.io/arkid/%20%E5%85%B6%E5%AE%83%E6%8F%92%E4%BB%B6/com_longgui_external_idp_wechatscan/'
logo=''
author='fanhe@longguikeji.com'
