# Generated by Django 3.1.7 on 2021-04-11 03:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='V1UserIdUUID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v1_user_id', models.IntegerField()),
                ('v1_user_uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('tenant_id', models.IntegerField()),
            ],
        ),
    ]
