package='com.longgui.register.notice'
name='隐私声明'
version='1.0'
labels='register_notice'
homepage='http://longguikeji.gitee.io/arkid/%20%E5%85%B6%E5%AE%83%E6%8F%92%E4%BB%B6/com_longgui_register_notice/'
logo=''
author='hanbin@jinji-inc.com'