# Generated by Django 3.2.9 on 2022-01-07 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0031_auto_20211231_0851'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeChatScanInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('openid', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='openid')),
                ('access_token', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='access_token')),
                ('refresh_token', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='refresh_token')),
                ('unionid', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='unionid(需要客户在开放平台打通了多个公众号)')),
                ('nickname', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='昵称')),
                ('avatar', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='头像')),
            ],
        ),
        migrations.CreateModel(
            name='WeChatScanUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('openid', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='openid')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenant.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wechatscan_user', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
