# Generated by Django 3.1.5 on 2021-01-16 15:07

from django.db import migrations


def add_default_superuser(apps, schema_editor):
    from inventory.models import User
    from django.contrib.auth.hashers import make_password

    User.objects.create(
        username='admin',
        password=make_password('admin'),
        first_name='Rock',
        last_name='Lee',
        email='insfocus@gmail.com',
        is_staff=True,
        is_superuser=True,
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_default_superuser),
    ]
