# Generated by Django 3.1.7 on 2021-04-05 11:19

from django.db import migrations


def add_default_tenant(apps, schema_editor):
    """
    add admin to platform tenant
    """
    from tenant.models import Tenant
    from inventory.models import User

    tenant = Tenant.active_objects.order_by("id").first()
    user = User.objects.order_by("id").first()
    if tenant and user:
        user.tenants.add(tenant)


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0002_add_default_tenant'),
    ]

    operations = [
        migrations.RunPython(add_default_tenant),
    ]
