# Generated by Django 4.0.6 on 2022-11-14 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_privateapp_values_data'),
        ('com_longgui_auto_form_fill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoformfilluser',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.app', verbose_name='应用'),
        ),
    ]
