package='com.longgui.app.protocol.radius.server'
name='radius服务端'
version='1.0'
labels=['radius']
homepage='http://longguikeji.gitee.io/arkid/%20%E5%85%B6%E5%AE%83%E6%8F%92%E4%BB%B6/com_longgui_app_protocol_radius_server/'
logo=''
author='hanbin@jinji-inc.com'