# Generated by Django 4.0.6 on 2022-11-03 06:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0032_expiringtoken_active_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('otp_secret', models.CharField(blank=True, default='', max_length=255, verbose_name='密钥')),
                ('otp_uri', models.CharField(blank=True, default='', max_length=255, verbose_name='二维码URI')),
                ('is_apply', models.BooleanField(default=False, verbose_name='是否启用')),
                ('target', models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='core.user')),
            ],
        ),
    ]
