# Generated by Django 3.2.8 on 2022-01-24 05:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0032_add_default_tenant_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalSaasArkIDBind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('company_name', models.CharField(max_length=255, verbose_name='本地ArkID公司名')),
                ('contact_person', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=128)),
                ('local_tenant_uuid', models.UUIDField(unique=True, verbose_name='本地ArkID UUID')),
                ('local_tenant_slug', models.SlugField(verbose_name='本地ArkID短链接标识')),
                ('local_host', models.URLField(verbose_name='本地ArkID链接')),
                ('saas_tenant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='tenant.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
