# Generated by Django 3.2.8 on 2022-01-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkid_saas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localsaasarkidbind',
            name='local_tenant_login_url',
            field=models.URLField(default='', verbose_name='本地ArkID登录链接'),
            preserve_default=False,
        ),
    ]
