# Generated by Django 3.2.8 on 2022-01-30 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arkid_saas', '0002_localsaasarkidbind_local_tenant_login_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localsaasarkidbind',
            name='local_tenant_login_url',
        ),
    ]
