# Generated by Django 3.2.13 on 2022-05-20 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extension', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approveaction',
            name='extension',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approve_action_set', related_query_name='actions', to='extension.extension', verbose_name='Extension'),
        ),
        migrations.AddField(
            model_name='approveaction',
            name='tenant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='approve_action_set', related_query_name='actions', to='core.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='appgroup',
            name='apps',
            field=models.ManyToManyField(blank=True, related_name='app_set', related_query_name='app', to='core.App', verbose_name='APP List'),
        ),
        migrations.AddField(
            model_name='appgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.appgroup'),
        ),
        migrations.AddField(
            model_name='appgroup',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='app',
            name='config',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='extension.tenantextensionconfig'),
        ),
        migrations.AddField(
            model_name='app',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'tenant')},
        ),
    ]
