# Generated by Django 4.0.3 on 2022-04-15 09:53

import arkid.core.token
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiringtoken',
            name='token',
            field=models.CharField(db_index=True, default=arkid.core.token.generate_token, max_length=40, unique=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='expiringtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='auth_token', serialize=False, to='core.user', verbose_name='User'),
        ),
    ]
