# Generated by Django 4.0.4 on 2022-04-21 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('extension', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='config',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='extension.tenantextensionconfig'),
        ),
        migrations.AddField(
            model_name='app',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'tenant')},
        ),
    ]
