# Generated by Django 3.2.13 on 2022-04-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scim_external_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='scim_external_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
