# Generated by Django 4.0.3 on 2022-04-18 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_expiringtoken_token_alter_expiringtoken_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='data',
        ),
    ]
