# Generated by Django 4.0.3 on 2022-04-28 11:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_permission_tenant_apipermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(max_length=100, verbose_name='Code')),
                ('category', models.CharField(choices=[('entry', 'entry'), ('api', 'API'), ('data', 'data'), ('group', 'group'), ('ui', 'UI'), ('other', 'other')], default='other', max_length=100, verbose_name='category')),
                ('is_system', models.BooleanField(default=True, verbose_name='System Permission')),
                ('app', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.app', verbose_name='APP')),
                ('group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.usergroup', verbose_name='UserGroup')),
                ('tenant', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'GroupPermission',
                'verbose_name_plural': 'GroupPermission',
            },
        ),
    ]
