# Generated by Django 4.0.3 on 2022-04-08 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tenant_options_alter_tenant_icon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'user'},
        ),
    ]
