# Generated by Django 3.2.13 on 2022-05-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_expiringtoken_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name='System Permission'),
        ),
    ]
