# Generated by Django 4.0.3 on 2022-04-18 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_app_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='type',
        ),
    ]
