# Generated by Django 3.2.13 on 2022-05-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_expiringtoken_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='icon',
            field=models.URLField(blank=True, null=True, verbose_name='icon'),
        ),
    ]
