# Generated by Django 3.2.13 on 2022-05-05 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220429_0847'),
        ('core', '0004_grouppermission'),
    ]

    operations = [
    ]
