# Generated by Django 3.2.13 on 2022-05-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_permission_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name='is open'),
        ),
    ]
