# Generated by Django 4.0.3 on 2022-04-18 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0001_initial'),
        ('core', '0004_remove_app_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='config',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='extension.tenantextensionconfig'),
        ),
    ]
