# Generated by Django 3.2.13 on 2022-05-06 07:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_0003_auto_20220429_0847_0004_grouppermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('result', models.CharField(blank=True, max_length=1024, null=True, verbose_name='权限结果')),
                ('is_update', models.BooleanField(default=False, verbose_name='是否更新')),
                ('app', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.app', verbose_name='App')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tenant', verbose_name='租户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': 'UserPermissionResult',
                'verbose_name_plural': 'UserPermissionResult',
            },
        ),
    ]
