# Generated by Django 4.0.3 on 2022-04-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_app_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='type',
            field=models.CharField(default='', max_length=128, verbose_name='type'),
        ),
    ]
