# Generated by Django 3.2.13 on 2022-05-26 06:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0002_remove_tenantextension_type'),
        ('core', '0005_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('extension_data', models.JSONField(blank=True, null=True, verbose_name='插件自带数据')),
                ('custom_data', models.JSONField(blank=True, null=True, verbose_name='')),
                ('extension', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='language_data', related_query_name='language_data', to='extension.extension', verbose_name='Extension')),
            ],
            options={
                'verbose_name': 'Language Data',
                'verbose_name_plural': 'Language Data',
            },
        ),
    ]
