# Generated by Django 3.2.13 on 2022-05-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tenant_icon'),
        ('core', '0005_alter_permission_is_open'),
    ]

    operations = [
    ]
