# Generated by Django 3.2.13 on 2022-05-06 11:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userpermissionresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('operation_id', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='操作id')),
                ('describe', models.JSONField(blank=True, default=dict, verbose_name='describe')),
                ('is_update', models.BooleanField(default=False, verbose_name='是否更新')),
            ],
            options={
                'verbose_name': 'API',
                'verbose_name_plural': 'API',
            },
        ),
        migrations.CreateModel(
            name='SystemPermission',
            fields=[
                ('sort_id', models.IntegerField(auto_created=True, default=0, verbose_name='Sort ID')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(max_length=100, verbose_name='Code')),
                ('category', models.CharField(choices=[('entry', 'entry'), ('api', 'API'), ('data', 'data'), ('group', 'group'), ('ui', 'UI'), ('other', 'other')], default='other', max_length=100, verbose_name='category')),
                ('is_system', models.BooleanField(default=True, verbose_name='System Permission')),
                ('operation_id', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Operation ID')),
                ('describe', models.JSONField(blank=True, default=dict, verbose_name='describe')),
                ('container', models.ManyToManyField(blank=True, related_name='system_permission_set', related_query_name='system_permission', to='core.SystemPermission', verbose_name='SystemPermission List')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.systempermission', verbose_name='Parent')),
                ('tenant', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'SystemPermission',
                'verbose_name_plural': 'SystemPermission',
            },
        ),
        migrations.RemoveField(
            model_name='grouppermission',
            name='app',
        ),
        migrations.RemoveField(
            model_name='grouppermission',
            name='group',
        ),
        migrations.RemoveField(
            model_name='grouppermission',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='permissions',
        ),
        migrations.AddField(
            model_name='permission',
            name='container',
            field=models.ManyToManyField(blank=True, related_name='permission_set', related_query_name='permission', to='core.Permission', verbose_name='Permission List'),
        ),
        migrations.AddField(
            model_name='permission',
            name='describe',
            field=models.JSONField(blank=True, default=dict, verbose_name='describe'),
        ),
        migrations.AddField(
            model_name='permission',
            name='operation_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Operation ID'),
        ),
        migrations.DeleteModel(
            name='ApiPermission',
        ),
        migrations.DeleteModel(
            name='GroupPermission',
        ),
        migrations.AddField(
            model_name='api',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.permission', verbose_name='权限'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='permission',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.systempermission'),
        ),
    ]
