# Generated by Django 3.2.13 on 2022-05-28 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_languagedata'),
        ('core', '0006_merge_20220526_1647'),
    ]

    operations = [
    ]
