# Generated by Django 4.0.3 on 2022-04-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_app_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmptyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelManagers(
            name='app',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='appgroup',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='approve',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='permission',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='tenantconfig',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='usergroup',
            managers=[
            ],
        ),
    ]
