# Generated by Django 4.0.4 on 2022-04-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_app_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmptyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
