# Generated by Django 3.2.13 on 2022-05-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20220526_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='slug'),
        ),
    ]
