# Generated by Django 3.2.13 on 2022-05-07 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220506_1125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='API',
        ),
    ]
