# Generated by Django 4.0.3 on 2022-04-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_emptymodel_alter_app_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='package',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='package'),
        ),
    ]
