# Generated by Django 3.2.13 on 2022-05-10 09:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0005_tenantextension_type'),
        ('core', '0008_delete_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproveAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('path', models.CharField(max_length=100, verbose_name='Request Path')),
                ('method', models.CharField(max_length=50, verbose_name='Request Method')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('extension', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approve_action_set', related_query_name='actions', to='extension.extension', verbose_name='Extension')),
                ('tenant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='approve_action_set', related_query_name='actions', to='core.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Approve',
                'verbose_name_plural': 'Approve',
            },
        ),
        migrations.CreateModel(
            name='ApproveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('environ', models.JSONField(verbose_name='Request Environ')),
                ('body', models.BinaryField(verbose_name='Request Body')),
                ('status', models.CharField(choices=[('wait', 'Wait'), ('pass', 'Pass'), ('deny', 'Deny')], default='wait', max_length=100, verbose_name='Status')),
                ('action', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='approve_request_set', related_query_name='requests', to='core.approveaction', verbose_name='Request Action')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approve_request_set', related_query_name='requests', to='core.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Approve',
                'verbose_name_plural': 'Approve',
            },
        ),
    ]
