# Generated by Django 3.2.13 on 2022-05-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='is_update',
            field=models.BooleanField(default=False, verbose_name='是否更新'),
        ),
        migrations.AddField(
            model_name='systempermission',
            name='is_update',
            field=models.BooleanField(default=False, verbose_name='是否更新'),
        ),
    ]
