# Generated by Django 4.0.3 on 2022-04-21 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_emptymodel'),
        ('core', '0008_app_package'),
    ]

    operations = [
    ]
