# Generated by Django 3.2.13 on 2022-05-09 11:18

import arkid.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220509_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systempermission',
            name='sort_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Sort ID'),
        ),
    ]
