# Generated by Django 3.2.13 on 2022-06-01 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_avatar'),
        ('core', '0009_app_entry_permission'),
    ]

    operations = [
    ]
