# Generated by Django 3.2.13 on 2022-06-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20220601_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='icon',
            field=models.URLField(blank=True, null=True, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_platform_user',
            field=models.BooleanField(default=False, verbose_name='Is Platform User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=128, verbose_name='Username'),
        ),
    ]
