# Generated by Django 3.2.13 on 2022-06-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220601_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='systempermission',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name='is open'),
        ),
    ]
