# Generated by Django 3.2.13 on 2022-05-11 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_approveaction_approverequest'),
        ('core', '0011_alter_systempermission_sort_id'),
    ]

    operations = [
    ]
