# Generated by Django 3.2.13 on 2022-06-02 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_accountlifecrontab'),
        ('core', '0012_systempermission_is_open'),
    ]

    operations = [
    ]
