# Generated by Django 3.2.13 on 2022-05-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20220511_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='sort_id',
            field=models.IntegerField(default=0, verbose_name='Sort ID'),
        ),
    ]
