# Generated by Django 3.2.13 on 2022-05-18 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0005_tenantextension_type'),
        ('core', '0013_permission_sort_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='config',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='extension.tenantextensionconfig'),
        ),
    ]
