# Generated by Django 3.2.13 on 2022-05-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_permission_sort_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systempermission',
            name='sort_id',
            field=models.IntegerField(default=-1, verbose_name='Sort ID'),
        ),
    ]
