# Generated by Django 3.2.13 on 2022-06-14 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20220602_0918'),
        ('core', '0013_platform'),
    ]

    operations = [
    ]
