# Generated by Django 3.2.13 on 2022-06-14 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_casbinrule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CasBinRule',
        ),
    ]
