# Generated by Django 3.2.13 on 2022-05-18 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_systempermission_sort_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approveaction',
            options={'verbose_name': 'Approve Action', 'verbose_name_plural': 'Approve Action'},
        ),
        migrations.AlterModelOptions(
            name='approverequest',
            options={'verbose_name': 'Approve Request', 'verbose_name_plural': 'Approve Request'},
        ),
        migrations.DeleteModel(
            name='Approve',
        ),
    ]
