# Generated by Django 3.2.13 on 2022-05-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_systempermission_sort_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermissionresult',
            name='is_update',
        ),
        migrations.AddField(
            model_name='userpermissionresult',
            name='is_self_create',
            field=models.BooleanField(default=False, verbose_name='是否是自建的权限结果'),
        ),
    ]
