# Generated by Django 3.2.13 on 2022-05-17 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220517_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermissionresult',
            name='is_self_create',
        ),
    ]
