# Generated by Django 3.2.13 on 2022-05-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_userpermissionresult_is_self_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='sort_id',
            field=models.IntegerField(default=-1, verbose_name='Sort ID'),
        ),
    ]
