# Generated by Django 3.2.13 on 2022-05-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_permission_sort_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True, unique=True, verbose_name='slug'),
        ),
    ]
