# Generated by Django 3.2.13 on 2022-07-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_approveaction_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='arkstore_app_id',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Arkstore app id'),
        ),
    ]
