# Generated by Django 3.2.13 on 2022-05-19 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_app_config'),
        ('core', '0017_alter_permission_sort_id'),
    ]

    operations = [
    ]
