# Generated by Django 3.2.13 on 2022-05-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_tenant_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='tenant_user_set', related_query_name='user', to='core.User'),
        ),
    ]
