# Generated by Django 4.0.6 on 2022-07-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_app_arkstore_app_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='approverequest',
            name='request_get',
            field=models.JSONField(default={}, null=True, verbose_name='Request GET'),
        ),
        migrations.AddField(
            model_name='approverequest',
            name='request_path',
            field=models.CharField(default='', max_length=255, verbose_name='Request Path'),
        ),
        migrations.AddField(
            model_name='approverequest',
            name='request_post',
            field=models.JSONField(default={}, null=True, verbose_name='Request POST'),
        ),
    ]
