# Generated by Django 3.2.13 on 2022-05-20 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220518_1036'),
        ('core', '0018_merge_20220519_0223'),
        ('core', '0019_alter_tenant_users'),
    ]

    operations = [
    ]
