# Generated by Django 3.2.13 on 2022-08-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_approverequest_request_get_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='frontend_url',
            field=models.URLField(blank=True, default='', max_length=128, null=True, verbose_name='ArkId访问地址'),
        ),
    ]
