# Generated by Django 3.2.13 on 2022-08-17 01:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0008_tenantextension_is_rented'),
        ('core', '0020_platform_frontend_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('title', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='title')),
                ('content', models.TextField(blank=True, default='', max_length=256, null=True, verbose_name='content')),
                ('readed_status', models.BooleanField(default=False, verbose_name='readed_status')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extension.tenantextensionconfig', verbose_name='Source')),
                ('tenant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'message',
            },
        ),
    ]
