# Generated by Django 3.2.13 on 2022-08-17 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0008_tenantextension_is_rented'),
        ('core', '0021_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extension.tenantextensionconfig', verbose_name='Source'),
        ),
    ]
