# Generated by Django 3.2.13 on 2022-08-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_message_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='source',
        ),
        migrations.RemoveField(
            model_name='message',
            name='tenant',
        ),
        migrations.AddField(
            model_name='message',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='url'),
        ),
    ]
