# Generated by Django 3.2.13 on 2022-08-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20220821_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='frontend_url',
            field=models.URLField(blank=True, default=None, max_length=128, null=True, verbose_name='ArkId访问地址'),
        ),
    ]
