# Generated by Django 3.2.13 on 2022-08-30 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_platform_frontend_url'),
        ('core', '0024_message_sender'),
    ]

    operations = [
    ]
