# Generated by Django 3.2.13 on 2022-09-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_apppermissionresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='arkstore_category_id',
            field=models.IntegerField(default=None, null=True, verbose_name='ArkStore分类ID'),
        ),
    ]
