# Generated by Django 4.0.6 on 2022-09-16 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_app_arkstore_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='approverequest',
            name='tenant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approve_request_set', related_query_name='requests', to='core.tenant', verbose_name='Tenant'),
        ),
    ]
