# Generated by Django 3.2.13 on 2022-09-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_approverequest_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='is_open_other_user',
            field=models.BooleanField(default=False, verbose_name='is open other user'),
        ),
        migrations.AddField(
            model_name='systempermission',
            name='is_open_other_user',
            field=models.BooleanField(default=False, verbose_name='is open other user'),
        ),
    ]
