# Generated by Django 3.2.13 on 2022-09-28 06:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20220921_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPersonalSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('settings', models.JSONField(default={}, verbose_name='用户个人设置')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tenant', verbose_name='租户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': 'UserPersonalSettings',
                'verbose_name_plural': 'UserPersonalSettings',
            },
        ),
    ]
