# Generated by Django 3.2.13 on 2022-10-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_userpersonalsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(blank=True, max_length=24, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
