# Generated by Django 4.0.6 on 2022-11-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_expiringtoken_active_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appgroup',
            name='apps',
            field=models.ManyToManyField(blank=True, related_name='appgroup_set', related_query_name='appgroup', to='core.app', verbose_name='APP List'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='all_tenant_set', related_query_name='all_tenant', to='core.user'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='usergroup_set', related_query_name='usergroup', to='core.user', verbose_name='User List'),
        ),
    ]
