# Generated by Django 4.0.6 on 2022-12-21 02:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0013_extension_expired'),
        ('core', '0037_openpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScimSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('start_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
                ('users_created', models.IntegerField(blank=True, default=0, null=True, verbose_name='New Users Created')),
                ('users_deleted', models.IntegerField(blank=True, default=0, null=True, verbose_name='Users Deleted')),
                ('groups_created', models.IntegerField(blank=True, default=0, null=True, verbose_name='New Groups Created')),
                ('groups_deleted', models.IntegerField(blank=True, default=0, null=True, verbose_name='Groups Deleted')),
                ('error', models.TextField(blank=True, null=True, verbose_name='SCIM Sycn error')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extension.tenantextensionconfig')),
            ],
            options={
                'verbose_name': 'Scim Sync Logs',
                'verbose_name_plural': 'Scim Sync Logs',
            },
        ),
    ]
