# Generated by Django 4.0.6 on 2023-01-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_scimsynclog'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='skip_token_verification',
            field=models.BooleanField(default=False, verbose_name='Skip Token Verification'),
        ),
    ]
