package='com.longgui.app.protocol.ldapserver'
name='LDAP server'
version='1.1'
labels=['ldap']
homepage='http://longguikeji.gitee.io/arkid/%20%E5%85%B6%E5%AE%83%E6%8F%92%E4%BB%B6/com_longgui_app_protocol_ldapserver/'
logo=''
author='guancyxx@guancyxx.cn'