# Generated by Django 3.2 on 2021-05-22 08:55

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0002_auto_20210220_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='constant_value',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='schema',
            name='scim_path',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='schema',
            name='sub_attrs',
            field=jsonfield.fields.JSONField(blank=True, default={}, null=True),
        ),
    ]
