# Generated by Django 3.2.4 on 2021-06-14 10:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0003_auto_20210614_1035'),
        ('schema', '0003_auto_20210522_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schema',
            old_name='scim_path',
            new_name='default_value',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='default_value_if_is_none',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='description',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='name',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='sub_attrs',
        ),
        migrations.AddField(
            model_name='schema',
            name='apply_type',
            field=models.IntegerField(choices=[(0, 'Always'), (1, 'Only during creation')], default=0),
        ),
        migrations.AddField(
            model_name='schema',
            name='provisioning_config',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='app_profile_mappings', to='provisioning.config'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schema',
            name='mapping_type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Direct'), (2, 'Constant')], default=0),
        ),
        migrations.CreateModel(
            name='AppProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=128)),
                ('type', models.IntegerField(choices=[(0, 'Boolean'), (1, 'Datetime'), (2, 'Integer'), (3, 'String')], default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_required', models.BooleanField(default=False)),
                ('multi_value', models.BooleanField(default=False)),
                ('exact_case', models.BooleanField(default=False)),
                ('provisioning_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_profile', to='provisioning.config')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
