# Generated by Django 3.2.6 on 2021-08-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0004_auto_20210614_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appprofile',
            name='type',
            field=models.CharField(choices=[('boolean', 'Boolean'), ('datetime', 'Datetime'), ('integer', 'Integer'), ('string', 'String')], default='string', max_length=128),
        ),
        migrations.AlterField(
            model_name='schema',
            name='apply_type',
            field=models.CharField(choices=[('always', 'Always'), ('created', 'Only during creation')], default='always', max_length=128),
        ),
        migrations.AlterField(
            model_name='schema',
            name='mapping_type',
            field=models.CharField(choices=[('none', 'None'), ('direct', 'Direct'), ('constant', 'Constant')], default='direct', max_length=128),
        ),
    ]
