# Generated by Django 3.2.13 on 2022-05-19 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('com_longgui_case', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseuser',
            name='user',
        ),
    ]
