# Generated by Django 3.2.13 on 2022-08-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_longgui_case', '0002_alter_caseuser_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Nickname'),
        ),
    ]
