# Generated by Django 3.2.13 on 2022-05-19 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220519_1357'),
        ('com_longgui_case', '0002_remove_caseuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseuser',
            name='target',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='com_longgui_case_CaseUser', to='core.user'),
        ),
    ]
