# Generated by Django 3.2.13 on 2022-06-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_longgui_case', '0003_rename_user_caseuser_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseuser',
            name='nickname',
            field=models.CharField(max_length=128, verbose_name='Nickname'),
        ),
    ]
