package='com.longgui.auto.auth.kerberos'
name='Kerberos自动登录'
version='1.0'
labels='auto-auth-kerberos'
homepage='http://longguikeji.gitee.io/arkid/%20%E5%85%B6%E5%AE%83%E6%8F%92%E4%BB%B6/com_longgui_auto_auth_kerberos/'
logo=''
author='fanhe@longguikeji.com'
