# Generated by Django 3.2.8 on 2022-01-10 08:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application_group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationgroup',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='唯一标识'),
        ),
    ]
