# Generated by Django 4.0.6 on 2022-11-10 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_expiringtoken_active_date'),
        ('com_longgui_app_proxy_nginx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nginxapp',
            name='target',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='core.app'),
        ),
    ]
