# Generated by Django 4.0.6 on 2022-11-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_longgui_app_proxy_nginx', '0002_alter_nginxapp_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='nginxapp',
            name='nginx_config_created',
            field=models.BooleanField(default=False, verbose_name='Nginx config created'),
        ),
        migrations.AddField(
            model_name='nginxapp',
            name='nginx_config_deleted',
            field=models.BooleanField(default=False, verbose_name='Nginx config deleted'),
        ),
    ]
