# Generated by Django 3.2.13 on 2022-07-27 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyGrantingTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=255, unique=True, verbose_name='ticket')),
                ('expires', models.DateTimeField(verbose_name='expires')),
                ('consumed', models.DateTimeField(null=True, verbose_name='consumed')),
                ('iou', models.CharField(max_length=255, unique=True, verbose_name='iou')),
            ],
            options={
                'verbose_name': 'proxy-granting ticket',
                'verbose_name_plural': 'proxy-granting tickets',
            },
        ),
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=255, unique=True, verbose_name='ticket')),
                ('expires', models.DateTimeField(verbose_name='expires')),
                ('consumed', models.DateTimeField(null=True, verbose_name='consumed')),
                ('service', models.CharField(max_length=255, verbose_name='service')),
                ('primary', models.BooleanField(default=False, verbose_name='primary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user', verbose_name='user')),
            ],
            options={
                'verbose_name': 'service ticket',
                'verbose_name_plural': 'service tickets',
            },
        ),
        migrations.CreateModel(
            name='ProxyTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=255, unique=True, verbose_name='ticket')),
                ('expires', models.DateTimeField(verbose_name='expires')),
                ('consumed', models.DateTimeField(null=True, verbose_name='consumed')),
                ('service', models.CharField(max_length=255, verbose_name='service')),
                ('granted_by_pgt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='com_longgui_app_protocol_cas_server.proxygrantingticket', verbose_name='granted by proxy-granting ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user', verbose_name='user')),
            ],
            options={
                'verbose_name': 'proxy ticket',
                'verbose_name_plural': 'proxy tickets',
            },
        ),
        migrations.AddField(
            model_name='proxygrantingticket',
            name='granted_by_pt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='com_longgui_app_protocol_cas_server.proxyticket', verbose_name='granted by proxy ticket'),
        ),
        migrations.AddField(
            model_name='proxygrantingticket',
            name='granted_by_st',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='com_longgui_app_protocol_cas_server.serviceticket', verbose_name='granted by service ticket'),
        ),
        migrations.AddField(
            model_name='proxygrantingticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user', verbose_name='user'),
        ),
    ]
