# Generated by Django 3.2.13 on 2022-08-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_longgui_external_idp_wechatwork', '0002_auto_20220824_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wechatworkuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='wechatworkuser',
            name='nickname',
        ),
        migrations.AddField(
            model_name='wechatworkuser',
            name='wechatwork_avatar',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='wechatworkuser',
            name='wechatwork_nickname',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='昵称'),
        ),
    ]
