# Generated by Django 4.0.3 on 2022-04-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_longgui_password_auth_factor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpassword',
            name='password',
            field=models.CharField(max_length=256, verbose_name='Password'),
        ),
    ]
