# Generated by Django 3.2.13 on 2022-05-19 14:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220519_1357'),
        ('com_longgui_password_auth_factor', '0002_alter_userpassword_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpassword',
            name='user',
        ),
        migrations.AddField(
            model_name='userpassword',
            name='target',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='com_longgui_password_auth_factor_UserPassword', to='core.user'),
        ),
        migrations.AlterField(
            model_name='userpassword',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
