# Generated by Django 3.2 on 2021-05-25 12:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gitee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiteeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('gitee_user_id', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Gitee ID')),
                ('access_token', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='access_token')),
                ('refresh_token', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='refresh_token')),
            ],
        ),
    ]
