# Generated by Django 3.2.6 on 2021-08-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_rules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantauthrule',
            name='type',
            field=models.CharField(default=None, max_length=100, verbose_name='类型'),
            preserve_default=False,
        ),
    ]
