package='com.longgui.auth.factor.email'
name='EMAIL认证因素'
version='1.0'
labels=['email', 'auth_factor']
homepage='http://longguikeji.gitee.io/arkid/%20%E5%85%B6%E5%AE%83%E6%8F%92%E4%BB%B6/com_longgui_auth_factor_email/'
logo=''
author='guancyxx@guancyxx.cn'