# Generated by Django 4.0.6 on 2022-11-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_longgui_auth_factor_scan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userqrcode',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='userqrcode',
            name='status',
            field=models.CharField(choices=[('created', 'QRCode Created'), ('scanned', 'QRCode Scanned'), ('confirmed', 'QRCode Confirmed'), ('canceled', 'QRCode Canceled')], default='created', max_length=50, verbose_name='Status'),
        ),
    ]
