# Generated by Django 4.0.6 on 2022-09-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_longgui_logging_mysql', '0003_tenantlogconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='is_tenant_admin',
            field=models.BooleanField(blank=True, default=False, verbose_name='是否管理员日志'),
        ),
        migrations.AlterField(
            model_name='log',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='日志数据'),
        ),
    ]
