package = 'com.longgui.scim.sync.dingding'
name='钉钉用户数据同步'
version='1.0'
labels='scim sync'
homepage='http://longguikeji.gitee.io/arkid/%20%E5%85%B6%E5%AE%83%E6%8F%92%E4%BB%B6/com_longgui_scim_sync_dingding/'
logo=''
author='hanbin@longguikeji.com'
