# Generated by Django 3.2.13 on 2022-05-31 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_tenant_slug'),
        ('com_longgui_external_idp_github', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubuser',
            name='target',
        ),
        migrations.AddField(
            model_name='githubuser',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='com_longgui_external_idp_github_githubuser', to='core.user'),
        ),
    ]
