package='com.longgui.account.active'
name="账号启停控制插件"
version='1.0'
labels='account'
homepage='http://longguikeji.gitee.io/arkid/%20%E5%85%B6%E5%AE%83%E6%8F%92%E4%BB%B6/com_longgui_account_active/'
logo=''
author='guancyxx@guancyxx.cn'
