# Generated by Django 3.2.8 on 2022-01-14 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_alter_app_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('title', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='标题')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('content', models.TextField(verbose_name='内容')),
                ('url', models.URLField(blank=True, null=True, verbose_name='链接')),
                ('type', models.CharField(help_text='支持的分类有notice通知,ticket工单，announcement公告', max_length=100, verbose_name='类别')),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='app.app', verbose_name='来源应用')),
                ('users', models.ManyToManyField(null=True, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '消息',
            },
        ),
    ]
