# Generated by Django 3.2.8 on 2022-01-10 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='users',
            field=models.ManyToManyField(null=True, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
    ]
