# Generated by Django 3.2.8 on 2022-01-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_alter_message_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='链接'),
        ),
    ]
