# Generated by Django 3.1.7 on 2021-03-28 14:03

from django.db import migrations


def add_default_enabled_extensions(apps, schema_editor):
    from extension.models import Extension
    from django.contrib.auth.hashers import make_password

    Extension.objects.get_or_create(
        type="inmem_cache",
        data={},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0002_auto_20210328_1033'),
    ]

    operations = [
        migrations.RunPython(add_default_enabled_extensions),
    ]
