# Generated by Django 3.1.7 on 2021-03-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0003_add_default_enabled_extensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Settings'),
        ),
    ]
