# Generated by Django 3.2.6 on 2021-08-24 09:20

from django.db import migrations


def add_default_enabled_extensions(apps, schema_editor):
    Extension = apps.get_model('extension', 'Extension')

    Extension.objects.get_or_create(
        type='password_login_register',
        data={},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0004_auto_20210329_0733'),
    ]

    operations = [
        migrations.RunPython(add_default_enabled_extensions),
    ]
