# Generated by Django 3.2.6 on 2021-10-09 11:14

from django.db import migrations


def add_default_enabled_extensions(apps, schema_editor):
    Extension = apps.get_model('extension', 'Extension')

    Extension.objects.get_or_create(
        type='oauth2_authorization_server',
        data={},
        is_active=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0006_auto_20211009_1114'),
    ]

    operations = [
        migrations.RunPython(add_default_enabled_extensions),
    ]
