# Generated by Django 4.0.6 on 2022-09-01 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_apppermissionresult'),
        ('com_longgui_logging_mysql', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='租户'),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.user', verbose_name='用户'),
        ),
    ]
