# Generated by Django 4.0.6 on 2022-09-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_longgui_logging_mysql', '0006_log_request_path_log_status_code_log_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='request_path',
            field=models.CharField(db_index=True, max_length=760, null=True),
        ),
    ]
