name: arkid v1 build

on:
  workflow_dispatch:
    inputs:
      prod_version:
        description: 'the tag of the image,src to release, like `1.2.3`'
        default: ''
        required: true
jobs:
  v1buildimage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: 'master'
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login harbor
      uses: docker/login-action@v1
      with:
        registry: harbor.longguikeji.com
        username: ${{ secrets.HARBORUSER }}
        password: ${{ secrets.HARBORPWD }}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUBUSERNAME }}
        password: ${{ secrets.DOCKERHUBPWD }}
    - id: get-short-id
      run: |
        id=$(echo ${{github.sha}})
        echo "::set-output name=id::${id: 0 :8}"
    - run: echo "${{steps.get-short-id.outputs.id}}"
    - id: set-pip
      run: |
        sed -i "s@https://mirrors.aliyun.com/pypi/simple@https://pypi.python.org/simple@g" requirements.txt;
        sed -i "s@https://mirrors.aliyun.com/pypi/simple@https://pypi.python.org/simple@g" requirements-dev.txt;
        sed -i "s@https://mirrors.aliyun.com/pypi/simple@https://pypi.python.org/simple@g" devops/pip.conf;
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: |
          ${{ secrets.ARK_RLS }}/arkid:${{ github.event.inputs.prod_version }}
          ${{ secrets.ARK_RLS }}/arkid:latest
          longguikeji/arkid:${{ github.event.inputs.prod_version }}
          longguikeji/arkid:latest
