name: mkdocszh
on:
  workflow_dispatch:
  push:
    branches:
      - feature-947
    paths:
      - 'docs/**'
      - 'extension_root/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install --disable-pip-version-check -r requirements.txt;
      - run: python manage.py migrate
      - run: mkdocs build -f docs/zh/mkdocs.yml
      - run: ls docs/zh/site
      - run: mkdocs gh-deploy -f docs/zh/mkdocs.yml -b gh-page-zh
